---
cachePersistence:
  enabled: true
  storageClass: truenas-ssd-nfs
  size: 20Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: beta.kubernetes.io/arch
              operator: In
              values:
                - amd64

resources:
  limits:
    memory: 8Gi
  requests:
    cpu: 100m
    memory: 800Mi

renovate:
  extraEnvVars:
    - name: GIT_CONFIG_COUNT
      value: "1"
    - name: GIT_CONFIG_KEY_0
      value: "safe.directory"
    - name: GIT_CONFIG_VALUE_0
      value: "*"
  mendRnvAcceptTos: y
  mendRnvPlatform: github
  mendRnvEndPoint: https://api.github.com/
  mendRnvWebhookURL: https://renovate.yanello.net/webhook
  existingSecret: renovate-secrets
  mendRnvCronJobSchedulerAll: "0 0 * * *"
  logLevel: DEBUG
  config: |-
    module.exports = {
      extends: [
        "config:best-practices",
        "mergeConfidence:all-badges",
        "default:automergeDigest",
      ],
      digest: {
        automerge: true,
      },
      ignoreTests: true,
      prBodyColumns: ["Package", "Update", "Change", "Package file"],
      rebaseWhen: "behind-base-branch",
      dependencyDashboard: true,
      major: {
        dependencyDashboardApproval: true,
      },
      minor: {
        automerge: true,
        dependencyDashboardApproval: false,
      },
      patch: {
        automerge: true,
        dependencyDashboardApproval: false,
      },
      dependencyDashboardOSVVulnerabilitySummary: "all",
      osvVulnerabilityAlerts: true,
      vulnerabilityAlerts: {
        enabled: true,
        vulnerabilityFixStrategy: "lowest",
      },
      argocd: {
        managerFilePatterns: ["argocd/**/*.yaml$", "talos/**/*.yaml$"],
      },
      kubernetes: {
        managerFilePatterns: ["argocd/**/*.yaml", "talos/**/*.yaml"],
      },
      packageRules: [
        {
          matchManagers: ["kustomize"],
          matchDatasources: ["helm"],
          pinDigests: false,
        },
        {
          matchDatasources: ["docker"],
          allowedVersions: "/^v?[0-9]+\\.[0-9]+/",
        },
        {
          matchDepNames: ["harbor.yanello.net/ghcr/hotio/prowlarr"],
          versioning: "regex:^release-(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)\\.(?<build>\\d+)$",
          allowedVersions: "/^release-[0-9]+\\.[0-9]+/",
        },
      ],
      ignorePaths: ["argocd/dev/**"],
      registryAliases: {
        "harbor.yanello.net/docker": "registry-1.docker.io",
        "harbor.yanello.net/ghcr": "ghcr.io",
        "harbor.yanello.net/quay": "quay.io",
        "harbor.yanello.net/lscr": "lscr.io",
      },
      "branchConcurrentLimit": 50,
      "prConcurrentLimit": 50,
      "prHourlyLimit": 0,
    };
