---
cachePersistence:
  enabled: true
  storageClass: longhorn
  size: 20Gi

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
podSecurityContext:
  fsGroup: 1000

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

resources:
  limits:
    memory: 8Gi
  requests:
    cpu: 100m
    memory: 800Mi

renovate:
  extraEnvVars:
    - name: MEND_RNV_DISK_USAGE_WARN_THRESHOLD
      value: "95"
  mendRnvAcceptTos: y
  mendRnvPlatform: github
  mendRnvEndPoint: https://api.github.com/
  mendRnvWebhookURL: https://renovate.yanello.net/webhook
  existingSecret: renovate-secrets
  mendRnvCronJobSchedulerAll: "0 * * * *"
  logLevel: DEBUG
