---
image:
  repository: harbor.yanello.net/docker/louislam/uptime-kuma
  tag: 2.5.0@sha256:a8610b3b4c38077922ba51b036691e06887d7cefd91fe620fd3d6d23d03dc240

volume:
  storageClassName: truenas-ssd-nfs
  accessMode: ReadWriteMany

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

externalDatabase:
  enabled: true
  hostname: mariadb
  port: 3306
  database: kuma
  existingSecret: mariadb-secrets
  existingSecretPasswordKey: MARIADB_PASSWORD
  existingSecretUsernameKey: MARIADB_USER
resources:
  requests:
    cpu: 20m
    memory: 192Mi
  limits:
    memory: 192Mi
