image:
  repository: harbor.yanello.net/docker/louislam/uptime-kuma
  tag: 2.3.2@sha256:9aeb4e51d038047f414309c77a1af553281ca535723cb88907d907269d0a908e

volume:
  storageClassName: truenas-ssd-nfs
  accessMode: ReadWriteMany

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

externalDatabase:
  enabled: true
  hostname: mariadb
  port: 3306
  database: kuma
  existingSecret: mariadb-secrets
  existingSecretPasswordKey: MARIADB_PASSWORD
  existingSecretUsernameKey: MARIADB_USER
