image:
  repository: harbor.yanello.net/docker/louislam/uptime-kuma
  tag: 2.3.1@sha256:358992958e8aab5cef16cda4fb8f2ef862091b9080caaf967a94991e89a260fb

volume:
  storageClassName: truenas-ssd-nfs
  accessMode: ReadWriteMany

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

externalDatabase:
  enabled: true
  hostname: mariadb
  port: 3306
  database: kuma
  existingSecret: mariadb-secrets
  existingSecretPasswordKey: MARIADB_PASSWORD
  existingSecretUsernameKey: MARIADB_USER
