---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:eFYWRq9SDZVNMEMfpVZevRVD+PWkQLo2JGkuf9cOy+pP/P0L0RmaRfaq0eNyk0kVYVMnNfM=,iv:Dz1m954jx8bCXXMJHRcpohfmsys8II8+sEhVWfdftFg=,tag:XN11n3fFJDwHzB51H3mJjw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-10-02T12:43:23Z"
  mac: ENC[AES256_GCM,data:ZOUtNSXfP56uoc6b4jobm3S/STS1AfZgNx3sz72nxFAxFoZiRRiY9w5aVh5kBtQ0+Aj0E4bq0LGfAR9VPxa9lKyKGYZlydJrwYN2utxj+tSsJOSKfuI0Hq1LRPmldrU/2oRKIKBVR0NkFsgAVJvypbs0vEMjpXZJF4NMIK07xbg=,iv:3BTmeOpq++ShJ2F/7kCfFxsRaxEQJoJz42FRjxkH7fo=,tag:21UKZIulbYhxnC4qDRmu2g==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
