---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: SecretStore
  target:
    name: bitwarden-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: .*
