---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden
spec:
  provider:
    doppler:
      project: bitwarden
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            key: dopplerToken
