---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garmin-fetch
  labels:
    app: garmin-fetch
spec:
  serviceName: garmin-fetch
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: garmin-fetch
  template:
    metadata:
      labels:
        app: garmin-fetch
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: wait-for-influxdb
          image: curlimages/curl:latest@sha256:7c12af72ceb38b7432ab85e1a265cff6ae58e06f95539d539b654f2cfa64bb13
          envFrom:
            - configMapRef:
                name: garmin-config
          command: ["sh", "-c"]
          args:
            - |
              echo "curling http://${INFLUXDB_HOST}:${INFLUXDB_PORT}"
              until curl -s -f http://$(INFLUXDB_HOST):$(INFLUXDB_PORT)/ping; do
                echo "Waiting for InfluxDB..."
                sleep 5
              done
              echo "InfluxDB is ready!"
      containers:
        - image: harbor.yanello.net/ghcr/arpanghosh8453/garmin-fetch-data:latest@sha256:8b7955d3459a42c4cbc2cb7a1b201daed1f77ac959e9063c55b055ad12aecdf2
          imagePullPolicy: IfNotPresent
          name: garmin-fetch
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: MANUAL_START_DATE
              value: "2025-06-01"
          envFrom:
            - secretRef:
                name: garmin-secrets
            - configMapRef:
                name: garmin-config
          volumeMounts:
            - mountPath: /home/appuser/.garminconnect
              name: garmin-data
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: garmin-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: truenas-ssd-nfs
        resources:
          requests:
            storage: 1Gi
