---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garmin-fetch
  labels:
    app: garmin-fetch
spec:
  serviceName: garmin-fetch
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: garmin-fetch
  template:
    metadata:
      labels:
        app: garmin-fetch
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:1.37@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
          command: ["sh", "-c"]
          args:
            - |
              chown -R 1000:1000 /home/appuser/.garminconnect
              chmod -R 755 /home/appuser/.garminconnect
              echo "Applied permissions"
          volumeMounts:
            - mountPath: /home/appuser/.garminconnect
              name: garmin-data
          securityContext:
            runAsUser: 0
            runAsGroup: 0
        - name: wait-for-influxdb
          image: curlimages/curl:latest@sha256:c03110c736db81bbe1be0296f1f1608c81b954b01626bdfb0a8f84e5bd00ff3c
          envFrom:
            - configMapRef:
                name: garmin-config
          command: ["sh", "-c"]
          args:
            - |
              echo "curling http://${INFLUXDB_HOST}:${INFLUXDB_PORT}"
              until curl -f http://$(INFLUXDB_HOST):$(INFLUXDB_PORT)/ping; do
                echo "Waiting for InfluxDB..."
                sleep 5
              done
              echo "InfluxDB is ready!"
      containers:
        - image: harbor.yanello.net/ghcr/arpanghosh8453/garmin-fetch-data:v0.5.0@sha256:8e375feb3a38358ddd94167efd24dcc0e59821b650e0cbe24ac0c06d91bd1d2b
          imagePullPolicy: IfNotPresent
          name: garmin-fetch
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: MANUAL_START_DATE
              value: "2024-01-01"
          envFrom:
            - secretRef:
                name: garmin-secrets
            - configMapRef:
                name: garmin-config
          volumeMounts:
            - mountPath: /home/appuser/.garminconnect
              name: garmin-data
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: garmin-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: truenas-ssd
        resources:
          requests:
            storage: 10Mi
