---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airtrail
  name: airtrail
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: airtrail
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: airtrail
    spec:
      containers:
        - env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: airtrail-db-app
                  key: uri
          envFrom:
            - configMapRef:
                name: airtrail-config
            - secretRef:
                name: airtrail-secrets
          image: harbor.yanello.net/docker/johly/airtrail:v3.12.0@sha256:c5616704defabd82d2dde97e93a5417e59c7acfdb06c0e589209257543b50f8c
          imagePullPolicy: IfNotPresent
          name: airtrail
          resources:
            requests:
              cpu: 10m
              memory: 96Mi
            limits:
              memory: 128Mi
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/uploads
              name: uploads
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: airtrail-uploads
