---
apiVersion: v1
kind: Secret
metadata:
  name: airtrail-secrets
type: Opaque
stringData:
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:nV6EBs9Tis52hHyjU6sFRcTwqlmujIlEJ0BGKq/80TprFvyaZEDq1w==,iv:pVmAZV+mk+o+84kgKmoaGaDoizR+KFib/EH/Lfs4fow=,tag:2+hZYZelLNpu8ru4Wbwy/g==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:EgCVgGP2Tr2hMuSilfOxybMKvOrAUKwQ9sPGv/GgsqliWvZDHY+lN5vjs5Y067KGMeWkJW+S6Nb4Uybvj8WhuWnljdIZdK/xgoZM+AhXk0ewQyFKGRZVyxR+w3sJB7C8c9LBzDEcqnGUgkMyj3sUW29Nnkl9BW7rHl62k8dqc1k=,iv:bISfIwXDL2NVJMGLapgA8bHPmKLNUS2jozSvL2LrERc=,tag:20qDL8nnnoLWIZK8Syne9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-07-18T14:13:35Z"
  mac: ENC[AES256_GCM,data:FKewo6+yRWuOBmkXSiUv0pzLqWC8+IbtfFbe3R8acc5QwvzgYV+SwgVF5SvRkyMysjcs0Vg02Y3ClA3OXLr5JAdPRlrZS3oYNECICX0I152+fvnQPkbX+zCE2BhR6xFrg6si+O1Cm1yzFTn4DlDx62KX4dbnOzn27hUIAdrt5o4=,iv:3OjbYl4r1A+o+WoNOYRpv683cGvtkbTtgdrPCyUyKQY=,tag:UBnCQjY04yx2RdJgRJD1aQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.2
