---
apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-secrets
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:9IL5YjHrOw+QDg==,iv:QP8aD0iuXedeFJ93khef7UvKCWKxXZPuQFWvSGOG3E8=,tag:kFocf5MDVCGLskxjbUYSZw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:oHc+WH7rz7xgvYE9+DW6QSnIpjTGXHR33k9GxlhauAd3TrVw1WuWSGevbp7IAGdTcTyoIApZMcHVq0FxxH/f3w==,iv:0Yg1WrvqWiDkEIC158xfM5Y4ws5AyYkxT8jHT5QaJj0=,tag:g0FL9kkyu7X3PPFZhmU5LA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:lVBcxIOPr7UTnQ==,iv:szz3kN9o43c/LH0Epz6irmLwjdMaZRwggbgAJAWLkm0=,tag:99ZzOMcdZMEWQhPpFwoDBQ==,type:str]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:R+LjxT/cE3mL1ANS4uqTx84BiRIAuS6KFXIB/Vt6Hpuo9nhGrFy4GLZwatYqm3Hsjzq9wlYSLOG6DE5UsYACCg==,iv:nca77fum7diW0BP45KSo/9hPs72Pqn9SJ1ZzxdoLWEs=,tag:Yyp+rUhN4YNO19Q3Ava//g==,type:str]
  AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:bd/3EENBL6NH68VmwWLPAOLazQ3EMm6tv+TNleAyXwwEbY1w7SjQ3Lict//mK99hKsDAcyyzgDgGEhShoJZczrtINjmfbwlKQEdo3Ei+wlld6rRtsl/3J9dLxh0Z0HBm9hXbiZDnHnhqOwWzAsYAiiQxTASkFXqcy8Ie6ejw220=,iv:+fgFMDb9Jc6g66vdqFHDEoUwEq2qExuwZVaD/3w6GIA=,tag:IeXofeGgrErHrrZeYIDISA==,type:str]
  AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:jup9sHiXZ4c+LjetFutvTZVksytvngWlZL+2E6TNGlfpZ8ITZG6r0g==,iv:6R6ut+qKrOg4lgTtIJRpOeNyjZuv6PRMR6KGoXftWVI=,tag:OEug+a6jtbM09Ka2+egOEw==,type:str]
  CUSTOM_OPENAI_BASE_URL: ENC[AES256_GCM,data:xtogz9hBOYY7qPMfs65o41Zv4kIydBrUXtESZg==,iv:CKl3NfsnlHfHSiansD3aYXMG77uWdxOY0lTQw0rEvCM=,tag:uCOk1vYooFeI898dLhyxyw==,type:str]
  OPENAI_MODEL: ENC[AES256_GCM,data:rwfeKJFF9qg7b0Lcfw9RUdbGsTfhIbwcaT3LHg==,iv:emYJN8XSgoHn1yTTiNdoWt31NgK3eGVSAoMMYLVE7u0=,tag:hrY7yVAOWCzg5WhEiz1CdQ==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:HQkPNZx5zvjyq4PY2nT6OYKLIyyAv3fZC4xz+SIbuEtZ7Hv+9CCUZk9AAureMIBzKvv14nlheGp8EQ/JgtOG2Oq5iyJ8OAWDPA==,iv:1wcgDW/RHaGAVP12YqON4bqgCps6V/5SjbnoQFVEgVQ=,tag:yb3InMyVZB2LnpWWpZKD9Q==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T20:31:24Z"
  mac: ENC[AES256_GCM,data:4DxYK6hohJahwy+eeO3yMkxzqFK2FrnH9oFOp8VoLSRPp/rr8zDVrWZQ9tTDks/Zh+VM4Ylaj2JGAPltZdu+28acTtbWVqdLkt7jkhTTPRr0oFlwNzElnsLaJC603fx1l9SYbIUwKZTrQsIFyVoPejf1cU850Zy0NxccUETPjzc=,iv:mvY5K00s4QFsWKseUNkFNE10+utX3FLDS4f8YqsAsUE=,tag:cqW3rr4aacuheXtd/mNhUQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.12.1
