---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: calibre
  name: calibre
  annotations:
    lbipam.cilium.io/ips: 10.10.8.2
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    app: calibre
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shelfmark
  name: shelfmark
spec:
  ports:
    - name: "http"
      port: 8084
      targetPort: 8084
  selector:
    app: shelfmark
