---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: metube
spec:
  endpointSelector:
    matchLabels:
      app: metube
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: cilium
            k8s-app: cilium-envoy
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "443"
              protocol: UDP
