---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/http-route.yaml
  - ./manifests/runner.yaml
  - ./image-pull-secrets/app-set.yaml
  - ./manifests/cnpg.yaml

generators:
  - ./manifests/secret-generator.yaml

helmCharts:
  - name: forgejo
    repo: oci://code.forgejo.org/forgejo-helm
    version: "17.1.3"
    releaseName: forgejo
    namespace: forgejo
    valuesFile: ./manifests/values.yaml
