---
apiVersion: v1
kind: Secret
metadata:
  name: victorialogs-auth
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:rgiV4hvX,iv:dt3OG5kUuKjQqrboBsSrcSppC71iCIjwv2V0UAh+bGA=,tag:xne3i8rne63H18ADPNzzMw==,type:str]
  password: ENC[AES256_GCM,data:rI1gW6wDM3/YrYJKXdW3IaPpKXmFuPQo,iv:GGq5qdXYBl2bieOy2HX7qjQn/+GmHuGQmPNEKUrxy7M=,tag:9fX5+rq1r+RSnpOfDKeSmg==,type:str]
  authorization: ENC[AES256_GCM,data:qYtdXq2SC9Z2TZjWTZ2scj/+8Hxdlwdntry5jlD+IWiOsLKg+bqe8W9jKC2Mt/xPp1Q=,iv:PtBrN4tY8TC7sKEgGXyr0bmBDFBYeCs29D1XU4yieB8=,tag:ndJLuRtMv4op9+t1iFVxFA==,type:str]
  vl-instance-headers: ENC[AES256_GCM,data:OSXaDOsX9260zD4lKKECRcqooee/5x+QBo7Dh0+zbTcV2XY0hvPMa8Ube9RJCxX+7bfClY9s4G1wND9JWFek2w==,iv:6o/ZlPD+tp6U1+vpoEiIY+VpLwu6ku1PUAFTrjFHwzI=,tag:/wy0Xn3jqg2H6bhLd0i4cw==,type:str]
  vmlogs-password: ENC[AES256_GCM,data:8PjmanCZL0mhUNTTlfp5AO122wNRR07N,iv:KkEOk+VttbwSBy9s8Guro8FyPU+ev11gnQg5o0iwuyA=,tag:F607SJzFh5Zm/qqV0KlBmA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SXZnMitIOGYvM3hZNXk4
        aXRJTVAweXhKaHFPZ1pvRDJiRlljMkN1dWxnCnhUU05CMm5rdDRmS1Y4K3QrWHBH
        WWJSRnVzZEZ3SzAremZUZFJpTkdJSk0KLS0tIFBnMHlLNU1ZdkFUOHZVNVAvN1dn
        em1YRVBkR3ZvMjM2SkNsNmtzSDN2MEEKWp39oB+u1f41eKYm0dsdB9Vhib7UqcrK
        uY+MM6JdfV9lq9lhUL7gyWwWK2h1YAMRszC3OFybmjocEFpadSaYYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-10-05T13:18:44Z"
  mac: ENC[AES256_GCM,data:7Nc0arR+0ktGgw/LBP0nu47r77zluEZCsnMrq7JXU1flISeccep8eZXbLHoPC4xISTtK2wayPb0PFYtbGDuywvfCND2wYO/eHPbwcl1IWLEyV5OZ9QL9zHkQncrj+sWIEI+PAQrmT8oDVCk0aSHtDMbk83pXeL+oFVan8hCLDiI=,iv:1bHC6OgP3jRGAPxC8rn0w6VcZuEPZuMecEFazAny0eQ=,tag:GnkJYsDJn8ccEex5PgQwzw==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
