---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budgeting
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/myanello/homelab"
    path: "argocd/budgeting/manifests"
    targetRevision: "main"
  destination:
    name: in-cluster
    namespace: budgeting
  ignoreDifferences:
    - group: ""
      kind: Service
      jqPathExpressions:
        - .spec.selector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
