---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml

resources:
  - ./cnpg.yaml
  - ./httproute.yaml

helmCharts:
  - name: budgeting
    repo: oci://cw-myanello.cwcr.io/budgeting # oci://harbor.yanello.net/helm
    version: 0.1.1 # "1.19.3"
    releaseName: budgeting
    namespace: budgeting
    valuesFile: ./values.yaml
