---
apiVersion: v1
kind: Secret
metadata:
  name: budgeting-secrets
type: Opaque
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:NI/HNBysOC90sPZBOyiD6AkqIO/IIcWSlEW0HxCpeu57k/GSMbNjMw==,iv:mdSuNJ5YJ3nHW6TBiu9op3c4Y8RQhTpQ0QWJL5ba5Ew=,tag:vgk+xVAad4y4xm4Q8J20hg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/l2SHNKT3FQs8w4isLkZB/Kc1UON59Idv73qocobQrDlAxjdNFpcQDSKVWNnS7oCYDWf0yzFVG+cbJ+kikpiEINyazKp4WNhgCFwcBn1VEGblh/1hdZy4n4sD8S9cmMTrtSDRaytyPanLFZ/2FrRx0SCMma3QkKhw4Ht8Fc6yUQ=,iv:G1dH9eWE4WJ6X27R+SklhwKtuRF/Txl/6JttjTMW4oY=,tag:TuqjpZ1iZabUk5Weeljr3g==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-06T22:52:47Z"
  mac: ENC[AES256_GCM,data:ksUAgb9jjIvncACoZTz5TFRYdHIN71ay49FnGoTKIJyxc/IBuVyuzZS4kphLkYMXVgLd9CorXZOKUHHec5uGApw0HbHpprj7b+ZsCGoo+3NMtJl1Ci4uUY3ootW8Adm1UTFHLFElx4QWbbdUaO2BKcGwavKXb5L9oYxtpXtJ2AE=,iv:pG0BOcIJrjDQhMFgsEIKHQAq9Ugd8tdD8nNlC1s2knc=,tag:gKyidoWZBdVAbzlv9RzR3w==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.12.2
