---
config:
  db:
    driver: "postgres"
    # PostgreSQL
    host: "db-rw"
    port: "5432"
    name: "budgeting"
    sslmode: "disable"
    # Reference a pre-existing secret with DB_USER and DB_PASSWORD keys
    existingSecret: "db-app"
    existingSecretUserKey: user
    existingSecretPasswordKey: password
