---
apiVersion: v1
kind: Secret
metadata:
  name: ntopng-exporter-config
type: Opaque
stringData:
  ntopng-exporter.yaml: ENC[AES256_GCM,data:zG5I/02tzvL4ewRRFlqLxyRYzpUEkCJu9BJkHANQHDNpwlwAl6hRMKbz1n64ZGyVz2u4oyKO4eWQvqDgmfM3LkHcBBf2Je0mTVpDSYZzRxkYW8DvwgMLjXz9jwHfL+kENajQRT1hpXE8vrzXBuVsuLlfMx58umlRXZJcx+5IHXxYd2RtFt/mpTpyoPTUbmfTEKslk3Qt6DTKUN/3NnftU4p9JZIYuPi0K1w6EitGgS0BNErYPRdmZtFYmg5AESWosHSdp74HTubK0jLLgmiuSjvw+sbIa/0sNGdh79wiNm4uIQw9ScB2UQqrh7l/jMoKDjC8MpCW7XKvIPp0oFhgPzEbloQKYucximdR37N9Q1fWnpcXS/oz3TxLhxy6ikHnjZUeTHME/43oj0AhH02gNXnz91IB6uM4IM8OdYy2ObCcnW6KHWlwbxJeBVjl0QLaWZLBTn1gg5BM1odBVpg80yv2rL0DViA9Z0OXhB3XSBqrC+9xFpn5K4+njto678UVoumAOZiw8xh18KE4+B3ZXK5hAoU1A1EtVrfjJUu/EubnSuCy7AK0BY1EzhFoPkWLFL4MZkBL8m2fUW0UpvtpPpq81WacPeqNXE8MR6X6NlkZ0AiNDw3vddKEbKJHmNjriOq3VwChRxFvPelMHUFHhAYNJMqm1KJJQii8hVS7Mg==,iv:0CZZ4UoutTW1dr8FTwCeJuRy/rB7wY1qBRoZqevmGXM=,tag:TAPjkU0EAdPWBmhNJvyI6Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T0NyMGE0TU5hbERqOUE2
        Y0NuY3lGcHpZeFRsZTVENXRCaVlxcjg5VzFFCkdjZGVVZG9BQjM2Wnd1ekJMVlVS
        bndSUkFNR0F0YkN2WkkxRHJzT3JlUjAKLS0tIHNNcytiY3dsWCsrUU1EUlo3NUpV
        dENkZjNjN2t6TUVnZ2I4ZmdUdmR2Wk0K3MuQM8etJN/S9B47HL4EaW7QNFgt7sod
        bsQ5HLxt4R17mrVRQWq28qucvBQzCMuKKHm1fzjq4nMTpL083NpymA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-10-02T01:42:19Z"
  mac: ENC[AES256_GCM,data:VtbA8qRZNIaxZ2lvlYrls/FsZxbThoG2w9S+4yFD0BA+eY4BRN9jcvpmDFeKbmjs7e2KbxUXr8V6o9KCLZGfZKLKGoafZCZA03kUE0IDTRpTYJ5CR7VBBoh7ea7z/js1A+0911TeGwWdHrL8FFtjAsk4ySC1rO0/t8ro9jP0JLI=,iv:wALoKeO0mAC34dhErSsQsC8OU4bZTFbzUYzBgSJCHpk=,tag:nnW+unoD1rB/w54lx3KHjg==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
