---
ollama:
  enabled: true
  ollama:
    gpu:
      enabled: true
      type: 'nvidia'
      number: 1
  runtimeClassName: nvidia
  persistentVolume:
    enabled: true
    storageClass: truenas-ssd-nfs
  resources:
    requests:
      cpu: 10m
      memory: 192Mi
    limits:
      memory: 192Mi
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - marcus-server

tika:
  enabled: true

persistence:
  enabled: true
  storageClass: truenas-ssd-nfs
  accessMode: ReadWriteOnce
  size: 10Gi

pipelines:
  persistence:
    enabled: true
    storageClass: truenas-ssd-nfs
    accessMode: ReadWriteOnce
    size: 10Gi
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 96Mi
extraEnvVars:
  - name: OAUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: chat-secrets
        key: OAUTH_CLIENT_ID
  - name: OAUTH_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: chat-secrets
        key: OAUTH_CLIENT_SECRET
  - name: OAUTH_PROVIDER_NAME
    value: Authentik
  - name: OPENID_PROVIDER_URL
    valueFrom:
      secretKeyRef:
        name: chat-secrets
        key: OAUTH_PROVIDER_URL
  - name: ENABLE_OAUTH_SIGNUP
    value: "true"
  - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
    value: "true"
  - name: OPENAI_API_BASE_URL
    value: "http://vllm-router-service.vllm.svc.cluster.local:80/v1"
  - name: OPENAI_API_KEY
    value: "none"
redis:
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      memory: 16Mi
resources:
  requests:
    cpu: 10m
    memory: 768Mi
  limits:
    memory: 896Mi
initContainer:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
