---
apiVersion: v1
kind: Secret
metadata:
  name: atuin-secrets
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:ZBQ3zJ0=,iv:4+JOHd1ImuRiyv7uJikV7mtSy/auCoHX1X2TnsRb/x8=,tag:49b/G4cCpFmZDw65RzPfLA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:1jAKHkBCJsVTI6ORQY+KwuQb4ycZ01ap0DVaVdpZkxRGZ0aTHjA/iNuLa4uph7qVeDqVG6kfkMYVSF7Alsigj5ikJ0lNWVjqMK27AxkksHIDdH56BLLExDmrL5l4etHMTQ13fA2cmWlP03y0y07XQgBEnK/8Qjh8QJoFl7Jb/xI=,iv:McAIVfTYljiz+kC6eVAW9js6caQR5fHS6XxxCSX1HUU=,tag:7EOzMvGHAISSHI7ILpTpiw==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:832zPn4=,iv:HdL5X9Y9VaLmVjyIvDCOaDTnzKpFaWv2FdOywvd3jpM=,tag:Ny6wE/htcIS1GbhjRNY3PA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-06-25T13:56:30Z"
  mac: ENC[AES256_GCM,data:br8+fkIFNXcWMSZj2j+r4UoV7VBa0gOU6Vvm+8fnjkWV9KFJV7WJq704ThhqNQ2j9rHdXq5KR4m6mpYdMJcyjwplez490YeSxMDPf7yoTEBkBFqB7Q9cTbB5hcJxWRz0aTmgevpe/LTdsKx5lk99d6hyvpzslBCm1FQxCRZJ1Q4=,iv:sNkSJdghQNsb/9//dQ6Fd0Nqk2Lg4617PVe4tbfjy6E=,tag:m2xZOsCW5iuuX22fI64F9A==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
