resources:
  - ./vs.yaml
  - ./cm.yaml

patches:
  - target:
      kind: Deployment
      name: nextcloud
    patch: |-
      - op: add
        path: /spec/template/spec/hostNetwork
        value: true
      - op: add
        path: /spec/template/spec/dnsPolicy
        value: ClusterFirstWithHostNet        

generators:
  - ./secret-generator.yaml

helmCharts:
    - name: nextcloud
      repo: https://nextcloud.github.io/helm/
      version: "6.6.3"
      releaseName: nextcloud
      namespace: nextcloud
      valuesFile: ./values.yaml

images:
  - name: nextcloud
    newTag: 30.0.6@sha256:e158a20c4cfecfa07f755d5283a86064865a46195d6d556b6b6cbf97fa99c64a
  - name: docker.io/bitnami/mariadb
    newTag: '10.11@sha256:ab38eb8e04b1d286cd1fb268d08013bc7d25f9015a9c374594256bcd4a8d1556'
