resources:
  - ./vs.yaml
  - ./cm.yaml

patches:
  - target:
      kind: Deployment
      name: nextcloud
    patch: |-
      - op: add
        path: /spec/template/spec/hostNetwork
        value: true
      - op: add
        path: /spec/template/spec/dnsPolicy
        value: ClusterFirstWithHostNet        

generators:
  - ./secret-generator.yaml

helmCharts:
    - name: nextcloud
      repo: https://nextcloud.github.io/helm/
      version: "6.6.3"
      releaseName: nextcloud
      namespace: nextcloud
      valuesFile: ./values.yaml

images:
  - name: nextcloud
    newTag: 29.0.12@sha256:74a9024d61c8fae9a855fbdbd6c4f17e87da1e7c5944ae2ba419a0a29160eaac
  - name: docker.io/bitnami/mariadb
    newTag: '10.11@sha256:ab38eb8e04b1d286cd1fb268d08013bc7d25f9015a9c374594256bcd4a8d1556'
