---
apiVersion: v1
kind: Secret
metadata:
  name: bookorbit-secrets
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:IY3n6+xxZ3jb0tNVm14/bQ0LJ+GmKV1nR97v9hyWlPeO7wx85uzL/6cu7raMREOybhhGbqQOlvnxfLL1licg3w==,iv:8ZV723baTymf4BSxB7NHOuROW1rAplzwPSDJksGNe5M=,tag:z8jGeNwIekJ0P6UKHbG2hA==,type:str]
  SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:ezVE66mjAHs9ZCxvGNwbMvBNa6q64WSK5pWyASo1cbQ=,iv:yAYJIbvxYN4wGVhTzRKro/kf4JoVyAVjJhI2JAi9RqU=,tag:TZuPpjuDW72imJAnbyf6Dw==,type:str]
  AA_KEY: ENC[AES256_GCM,data:QmG/tw4uEnHWc6TEM+wlYpQc6HLkqnKMtCuFqf8=,iv:vTY4OzMbG5Ny+TJVUXFsmEZ3A82B1iZL33KkLBakv8o=,tag:xOLB5c+dNoYZ8U00ZdEMGQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSStDM3VNVmFZVE84RlRj
        L1JxSGgyMHBoZGgxd2NIeHJzYWZ5OWJUU3hrCmV5bTdzWnoyQlI2NTlmY29maGZP
        dTYrTTdEWWlleHFnSWdEdVYza3Z6UzgKLS0tIFdCOTNBNWJpZlQ4T2RCamMxYk1Y
        eEIxVjdndnAyTzRJN0NrNnFlUENqcUUKqq293XLEB/DEo81iNe6fsNocmRTKHui/
        8V6QGYlZ9aiP3TpFmIS6J4Zgn4bTwTtWiWkiWKXRoLv20uih9XWZZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-06-26T17:12:43Z"
  mac: ENC[AES256_GCM,data:rg++LFa1q1FIUYQaKquJVDeWKbfsvC5mxRy/EyPoK2Pdn91JUUtYNKXwzkI28f7xwIyAx0ObVEAuHgkSxRVYY5eisBOEJ0HDg2ghvP5MNCdGcHITUJqgBJ90LHeCwXlc798M1zmPE04K490A2hlH0n9r50JDx/zNg5u8TesUlyQ=,iv:Ke+8PQOoLb80STQLEU2wyv9ZC+L/0xCJuRXMxm60apo=,tag:zjXB4zaqWbuTqxjGtKL2ag==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
