---
apiVersion: v1
kind: Service
metadata:
  name: budgeting-preview
  labels:
    app.kubernetes.io/name: budgeting
    app.kubernetes.io/instance: budgeting
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: budgeting
    app.kubernetes.io/instance: budgeting
