---
apiVersion: v1
kind: Secret
metadata:
  name: budgeting-secrets
type: Opaque
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:NI/HNBysOC90sPZBOyiD6AkqIO/IIcWSlEW0HxCpeu57k/GSMbNjMw==,iv:mdSuNJ5YJ3nHW6TBiu9op3c4Y8RQhTpQ0QWJL5ba5Ew=,tag:vgk+xVAad4y4xm4Q8J20hg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/l2SHNKT3FQs8w4isLkZB/Kc1UON59Idv73qocobQrDlAxjdNFpcQDSKVWNnS7oCYDWf0yzFVG+cbJ+kikpiEINyazKp4WNhgCFwcBn1VEGblh/1hdZy4n4sD8S9cmMTrtSDRaytyPanLFZ/2FrRx0SCMma3QkKhw4Ht8Fc6yUQ=,iv:G1dH9eWE4WJ6X27R+SklhwKtuRF/Txl/6JttjTMW4oY=,tag:TuqjpZ1iZabUk5Weeljr3g==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:+ltuB/5rDCiEb0Y8y5YU3vmuVdTiBTnBwelExm9fkDG+niOJo7KsTdGCSJSWh3MW,iv:wPvHcgzPWcQfdmvccj1vfRSBA0MP0YsLBGhtxcgWVz0=,tag:vF/j8/R23/zlCQOym9ZKYQ==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:t1ZKkzyu5yVVMpx2HDCgG9XevJAdQtTIoS/Azi01NYv/yoTV0Rp78Jz+C6ClXzQh,iv:v93cLDAyaabV1J07Zj/r/vjFfbWHPBj9VsIiO47EHc0=,tag:L2OELSKhxFP70h46dnCd7w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-06-11T02:49:42Z"
  mac: ENC[AES256_GCM,data:E1d8V5KmDPqfop973j31xZl6VUB7pRBbMX/M6eCB3cBkxkltGQjSjjzD8YoMRrN94iLAt0ggyDrnNCHifuXslHzcVzu/PiKN0riU1WWf2VoE5CANZd/WEOJ4ywGKIOtooy+PKIkC5LYFBigYX7bOTavmQigwCkNCBv8vZYNjN8U=,iv:ih4aRKx1oMI7Ss0xiz7u1juYenz1uayPFL2Awz8YOKY=,tag:PDOmPbPUuOtoctaGle9WbA==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
