---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: truenas
spec:
  endpoints:
    - dnsName: truenas.yanello.net
      recordType: A
      recordTTL: 300
      targets:
        - 192.168.10.78
