apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: frigate-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./manifest/frigate-secret.enc.yaml