---
apiVersion: v1
kind: Secret
metadata:
  name: excalidash-secrets
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:QbhM4emCuyggwNwGMwABC/3QpcCKchh3x3F2STfMUBafkrtu9AhFHhUonCE=,iv:Z0WL+mEZeMW7I71Oyfqrqdwz8XS133t3U6ruhcEObHk=,tag:ayXWQ4cZ4ffdQyiRyE5JKA==,type:str]
  CSRF_SECRET: ENC[AES256_GCM,data:QA6hFAI7bkUFbxYndAhljZhZaQ08cYKhUE9sOZBjKa8lb5Ws55oK7dhVDW8=,iv:5riVf41IuSaIy4K9ifwHPaurYDyKlwg7Rceuih+WiR0=,tag:pFPlqcWOUlDeEoxodXnZ8Q==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:v/rVlP557ViuE+qgGvavfrEgP491xoL0iFmr0KzkJ57KCynBH1xgIg==,iv:ipLUlnioVRG7M7hd5ol9ulHyjE0I7Cr0qTfo8SHsF/c=,tag:xl2qnDGND83kClA/0EYy3Q==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:CJjhMTDhP+wCGy/j9fYXswiUYenpvWqhOokZBn3j4/EqB1lfYmNCSPAJYZRnX7Y4HWkR0JEMFPrUJYWAtuUI+LX5MSK38KieIrfhkZPM3TA9a0w3kNSrTR3FE4QyMcrom7kOMsxSB5PYXf2sv2+sUmCqsvwjhpx3oen6qRhIugM=,iv:vcu504kKToLgMGROAj9bGF/yRDDV56i3WBbQRIewYBE=,tag:cNQbtQ3ATeERA8qie7L9hA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMGgwb0dVdmJLaEJiUEUx
        L1NjSEFkdUxTVmVLZldIMFdCWGV4VjdwZWhZCml0aVcrQXY4aHBWem9jZmU0NlAr
        OXNTWEU1Tmg3UzcyYXU1RDloemVuSFEKLS0tIEpicFgvaXBsczFNKzRvSFNzaFAy
        SEQ5VHRXODNLYk1Ca1NUU3c4cmtNcHcKJbvB7KnLB0ztqlBRFS1uRh/khsViXVnY
        oULrW1jYY5IwRTEbbrPGW1UscW2pHaayj+mIXidA36UeUbMFciiCUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-08-22T14:51:53Z"
  mac: ENC[AES256_GCM,data:YdMXXfj+qJ2EOUWwkLHcVHHHzBwAG6JzUZ3JvGlTmMtEkdoP7CnDMQXGOir4xyqIZXKav/GwOkrnVlq4CZ+1zjIeAwGIox2tDqY9nRE6mr5tRs9pm9oirN8nPWPp2dhJvr6SAR7gGpUx1+vJN5gBR716Zzrg/DWylEp7MsODzuc=,iv:5mAXCTdyDjR2BPzYZzWR2JmpfYdoBbNySq8kdXRuQQE=,tag:uErhlmtxirTlYmrfr8SZCA==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
