---
apiVersion: v1
kind: Secret
metadata:
  name: excalidash-secrets
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:QbhM4emCuyggwNwGMwABC/3QpcCKchh3x3F2STfMUBafkrtu9AhFHhUonCE=,iv:Z0WL+mEZeMW7I71Oyfqrqdwz8XS133t3U6ruhcEObHk=,tag:ayXWQ4cZ4ffdQyiRyE5JKA==,type:str]
  CSRF_SECRET: ENC[AES256_GCM,data:QA6hFAI7bkUFbxYndAhljZhZaQ08cYKhUE9sOZBjKa8lb5Ws55oK7dhVDW8=,iv:5riVf41IuSaIy4K9ifwHPaurYDyKlwg7Rceuih+WiR0=,tag:pFPlqcWOUlDeEoxodXnZ8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMGgwb0dVdmJLaEJiUEUx
        L1NjSEFkdUxTVmVLZldIMFdCWGV4VjdwZWhZCml0aVcrQXY4aHBWem9jZmU0NlAr
        OXNTWEU1Tmg3UzcyYXU1RDloemVuSFEKLS0tIEpicFgvaXBsczFNKzRvSFNzaFAy
        SEQ5VHRXODNLYk1Ca1NUU3c4cmtNcHcKJbvB7KnLB0ztqlBRFS1uRh/khsViXVnY
        oULrW1jYY5IwRTEbbrPGW1UscW2pHaayj+mIXidA36UeUbMFciiCUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-08-22T14:24:09Z"
  mac: ENC[AES256_GCM,data:jfYqmRj4MqYUxsUYBah6iVC0voY3XdZ8JWjLO0SYsdIN8vPXqMXC/5wuNYu09P09wl/wQZVKihqSu96MoEhkpPlooRKf33Rmp/QfED/PBM+PeK4TCS0f/5JQIU6/vF7ohQhWn2y87qNOTy+UDKfoC87RY4X4zTTNdeqberqyHBc=,iv:4WAX4QxjluhL6kR+V+3zI2sKr/bZzzjho29iVK3BdhU=,tag:NO0kA8lDijX1x5DoZa/u7w==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
