---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-secrets
  namespace: mealie
type: Opaque
stringData:
  DB_ENGINE: ENC[AES256_GCM,data:2no2QqKuaiA=,iv:HTxpxoBGcBlO420ldDxKC0iTq5PK824BxbmTIzu3MRE=,tag:NIq9oYlmgg1z3tcFMSd9Jw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:W/VOGWUw,iv:PZ82MTVgc5/udX5PJFv/IOb56PkwX8z/RJ2Ijm1Y2eY=,tag:RHt1PKWf8SdDU8wBMKBs0g==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:N/Db5MfvSQugD5zXR9JBga5OXLSwP1Elh00pofKCToM=,iv:G1063qxjrtMhANIbJrOh3rToP5+bP6/OJnMrKjN8JUM=,tag:nZ8WTddlYlS1/spbpX92kQ==,type:str]
  POSTGRES_SERVER: ENC[AES256_GCM,data:EUtT9cfmTJA=,iv:bxb7rNZVqL3iu3FYqqfSCvHJ2Au43BIYmMDtIYIWc1A=,tag:gU3PLXQh8HAGuxLlFiobsA==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:e5UOXw==,iv:pzPSIgldN1EfdCxuvVB8he1afnWV0qmaSedwiZK/Fpc=,tag:KhOHfL8l1csqTvo0kEDm4w==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:LSE0xLCY,iv:Q7EfQyDgPVS1HKuyNap4g7MVLoK4RBAHJH3RKGpMLhw=,tag:lUT1tmEC6Rwu4NGjSub6QA==,type:str]
  OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:mi/370syY/7pwkWiD6hPTmmVjTZNOsmqG/VItn8J28F0IzpsZlwTKtV9+Hji+iALkIjIJFfdfCVNp8Vur26P2Hm+N/+jpeIVx6dH+QKbh0WBdgw=,iv:2DYz6wA0S5d+oiNgQj0N5MRxICiUd1OfQX03K0Ry8Y8=,tag:XPWmw2ogqMHqqaRLIYvMvw==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:8tAc6Z8ANNEmqrEXFytKk8hUCN7fI2/Il7ZxwwsQKMoBPhGk44oVMg==,iv:j9Svxc/U+BZcHHHx2xtpF3vUfxQcmstfrCSbXM7+Y/g=,tag:HMByvSUVq6sPPmgvuSKPeQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:GVds+/RW5403aVoVI6tXA1yDmuGcm9CtotwRjKx1PLRczrc4otPKDh9clHPfI8KpRkrI5bTLlIoKoBxO4owOV+Q3oBLpe4IzErSURsFxC6jlPKLc5Y2uBJKQj6YpTEiskxGzgdidfA5vgmj7/yNzOfwI7WUaUxIbgYXyyh09LwQ=,iv:H/M8lPW4N0dGKFIMrevBeEgsHf3+u81HLsTfKC6UFjg=,tag:ByaAv41ZvhRwSStBxYehHg==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:g0p1VZXFn18UFlaJ6yp46K/70kdbFNChUV1T1/U=,iv:5fAIGF9r30pxPwFtCK5010MpjT2bkZEce9kCxOQaVVY=,tag:N0K5Ypr9sy/2RmGoNIimgw==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:sFluSkOuDyBu6aK2HX/vklUDnKUPBKxbVNFIIBTMIKU9tGJhI5TIs6v5NAG5MZiyAnfcoNEGZyScwvxGlHhihiMNIiVrnzlgiw==,iv:wfbrg1/nYzT2N4IYyhp6oI6BcklY4MwZHikSDRrn2PE=,tag:Nr7XQXUpDbEBTeJiEv9dhA==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T16:45:12Z"
  mac: ENC[AES256_GCM,data:iYnEuSFkwmmjqIj/reBQt045pDc1qorlPqvVs00e8cdA8wza6Aj068ee1CMUaWfhwI2KX/086mp1HdjjULcl4pjt3hi7Db6SWxmp1juoSny9nDRlRdSP5CVOOCS0B/XR+37CCoVwvMe16HckJHcJh+UDdiu5A3VJvAhHL8kIKtE=,iv:3slvHhUWQov/iBSagPp1jA79X7Q6VGeemnGaY/zaST4=,tag:JOAmDN8LVHPcA5GyVc6Meg==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.12.1
