---
server:
  persistentVolume:
    enabled: true
    storageClassName: truenas-hdd
    vmServiceScrape:
      enabled: true
  retentionPeriod: 3d
  retentionDiskSpaceUsage: 2.5
  extraArgs:
    httpAuth.username: vmlogs
    httpAuth.password: file:///etc/victoria-logs-auth/password
  extraVolumes:
    - name: auth
      secret:
        secretName: victorialogs-auth
  extraVolumeMounts:
    - name: auth
      mountPath: /etc/victoria-logs-auth
      readOnly: true
  resources:
    requests:
      cpu: 10m
      memory: 192Mi
    limits:
      memory: 256Mi
