---
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi.hdd"

node:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "csp/oci"
      operator: "Exists"
      effect: "NoSchedule"
  driver:
    resources:
      requests:
        cpu: 30m
        memory: 96Mi
      limits:
        memory: 96Mi
    cleanup:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 64Mi
  csiProxy:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
  driverRegistrar:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi
controller:
  driver:
    image:
      tag: next
    resources:
      requests:
        cpu: 10m
        memory: 96Mi
      limits:
        memory: 96Mi
  csiProxy:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
  externalAttacher:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        memory: 16Mi
  externalProvisioner:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi
  externalResizer:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
  externalSnapshotter:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        memory: 16Mi
storageClasses:
  - name: truenas-hdd
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      # for block-based storage can be ext3, ext4, xfs
      # for nfs should be nfs
      fsType: xfs

      # if true, volumes created from other snapshots will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromSnapshots: "false"

      # if true, volumes created from other volumes will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromVolumes: "false"

    mountOptions: []
    secrets:
      provisioner-secret: null
      controller-publish-secret: null
      node-stage-secret: null
      #      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
      #      # if doing CHAP
      #      node-db.node.session.auth.authmethod: CHAP
      #      node-db.node.session.auth.username: foo
      #      node-db.node.session.auth.password: bar
      #
      #      # if doing mutual CHAP
      #      node-db.node.session.auth.username_in: baz
      #      node-db.node.session.auth.password_in: bar
      node-publish-secret: null
      controller-expand-secret: null
# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
# - name: freenas-iscsi-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  existingConfigSecret: democratic-secret
  config:
    driver: freenas-api-iscsi
