---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgis-trixie
spec:
  images:
    - major: 16
      image: ghcr.io/cloudnative-pg/postgis:16-3.6-standard-trixie@sha256:b31312862b2ee01ac08c672093737112aa109149a08ef3f744aa5ada3dcbc40e
    - major: 17
      image: ghcr.io/cloudnative-pg/postgis:17-3.6-standard-trixie@sha256:934143adde6b4358adeb6aaaa1b5c0173eb6e8f91aac909d564d8ffee749bc02
    - major: 18
      image: ghcr.io/cloudnative-pg/postgis:18-3.6-standard-trixie@sha256:1a21ed00da31fd7e44dd3830342d566dc0427b2f92d1d28be5c376de642f7424
---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 18
      image: docker.io/timescale/timescaledb-ha:pg18.1-ts2.25.0@sha256:9dcbd18e5cb966398ae19f3882fd5fb2e19b3cb98be54d290ab9f69c75bf0a8b
