---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgis-trixie
spec:
  images:
    - major: 16
      image: ghcr.io/cloudnative-pg/postgis:16-3.6-standard-trixie@sha256:1c79fc0bf80b10a32136a1f0d302c8068f3508496ac094436156eaa152aabd5d
    - major: 17
      image: ghcr.io/cloudnative-pg/postgis:17-3.6-standard-trixie@sha256:9ae4a1abaf21135ed6318bb0402b55a5c6d585e321265642e561d13af6573ff6
    - major: 18
      image: ghcr.io/cloudnative-pg/postgis:18-3.6-standard-trixie@sha256:8bcdc53bc981108406bdd8bdb1159a756fec128503b3bff9e35be7e7273e13df
---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 18
      image: docker.io/timescale/timescaledb-ha:pg18.1-ts2.25.0@sha256:9dcbd18e5cb966398ae19f3882fd5fb2e19b3cb98be54d290ab9f69c75bf0a8b
