---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgis-trixie
spec:
  images:
    - major: 16
      image: ghcr.io/cloudnative-pg/postgis:16-3.6-standard-trixie@sha256:087fc8aeadbbb71b1e154fffc4e08338cb7f67ab95439fcaedae049d091bfef8
    - major: 17
      image: ghcr.io/cloudnative-pg/postgis:17-3.6-standard-trixie@sha256:167fd85bfccee2eaf90d49a04abe13c6ab8e2922d392da90e549cbb4927c215f
    - major: 18
      image: ghcr.io/cloudnative-pg/postgis:18-3.6-standard-trixie@sha256:bd38ee75084394f8d0ebe8bc0d21f7d3fc4e22be8089d16f5f45751b0645f2a5
---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 18
      image: docker.io/timescale/timescaledb-ha:pg18.1-ts2.25.0@sha256:9dcbd18e5cb966398ae19f3882fd5fb2e19b3cb98be54d290ab9f69c75bf0a8b
