---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backblaze-cnpg-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: backblaze-cnpg-creds
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: BACKBLAZE_CNPG_KEY_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: BACKBLAZE_CNPG_SECRET_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
