---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-cnpg
spec:
  inheritedMetadata:
    annotations:
      backup.velero.io/backup-volumes: pgdata
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 18
  storage:
    size: 8Gi
    storageClass: truenas-ssd
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  affinity:
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
  plugins:
    - name: cnpg-plugin-barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: authentik-backups
  enableSuperuserAccess: true
