---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-cnpg
spec:
  inheritedMetadata:
    annotations:
      backup.velero.io/backup-volumes: pgdata
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 18
  storage:
    size: 8Gi
    storageClass: truenas-ssd
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  affinity:
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
  backup:
    barmanObjectStore:
      destinationPath: s3://myanello-cnpg/authentik
      endpointURL: https://s3.us-west-004.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: backblaze-cnpg-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backblaze-cnpg-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  enableSuperuserAccess: true
