apiVersion: v1
kind: Secret
metadata:
    name: harbor-secrets
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:a9jCMQ6VE/nzzYdSDUueupCqFGX3FaYbEsjVO3TaNVIZa+3U,iv:plwyBPM5PyS+nrX+/qGxzJ/ujSStJy1quPosHY5KL1c=,tag:3M1pJ1BWoK7Ggq4YROXZZg==,type:str]
    secret: ENC[AES256_GCM,data:3zQ4TcURI26/ByB/W/+O1g==,iv:59Xv5GUyTLPdFY8GyKYrCYCJmAceI1q5Yk9smqiXBoE=,tag:JN/VEJQiGh5QqOzF6zMmVQ==,type:str]
    CSRF_KEY: ENC[AES256_GCM,data:TjW6mqB55V2osJTgSmty7lu+Z5H1DMJD5USmA9sG04A=,iv:N6tZ8jk2Gba7ENFVg/v1851ZXuS8xKmuKGaigXZBhN4=,tag:4WA3FMLR7vjWL509WjK3bg==,type:str]
    JOBSERVICE_SECRET: ENC[AES256_GCM,data:j7gouelb6Hwi2ETq9Fs1xg==,iv:0K9y+IHowbr/IYOMrdD9/IYzMwRJ4SNpjsok+wiM4I0=,tag:5lmgUJnfNJwMyzO+1PB5xg==,type:str]
    REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:hrcC67PV8ayDSWuV7kO+GQ==,iv:pFjs4Dks1Ri9bbJwIcySZAr6RP2NtILNcZG+Ge4FGyc=,tag:ra/Kpy0w0HA/Q0Wv/N7qXA==,type:str]
    REGISTRY_PASSWD: ENC[AES256_GCM,data:81xVEuGySaGAm0i/4mXigM/QXKjWEqJp,iv:226gBhZtJiUiBjE5g3FICTDWU1bvaUJtNzsiUFTPQdg=,tag:u5JPr0UebxCesjZXIWGWhg==,type:str]
    REGISTRY_HTPASSWD: ENC[AES256_GCM,data:FU2ywTCOd2qCuGbA2EQVjTlSaRBSbcGGyJewbGia+sSVStU1dYA4n9nLaJ4oTEiE/7UyLUoGOFVG/v7h5o2LmTbGZpRO60qF4bB1v3+Pmdis,iv:7BN5qe2dqRGeYIdznZKJA71W3wxXcxsOUoR7/8S0WKU=,tag:JQpn1MoZeZt9Z32r3IAVag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwS1BXY2xpYU4vNllMdHN1
            dDdvd1gvWjZ1SElXWlA2by9nV043ZnZzWDJvCnphcWphUFkzY0p6cDJxYVpPbkZ4
            TXhNdWJ4dEJUQkdhbWlwdHFDTEx5N0kKLS0tIGxWMWNFTzhPWWwyU1Z5STJveTJF
            V2ZOajQveTFyQnhpckE5b25EY0FEMU0KiJDxngVIQjz+pT6wwwVnSulkj3FfGxZy
            bAE0nnRjDZSyyCV5AcxAwCLP+Jlsq5rHyC9Asiv6zAI0MxmiSeNN/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
    lastmodified: "2026-09-25T01:17:12Z"
    mac: ENC[AES256_GCM,data:P3N5HfWMJwfaaT+0hg5D6gPiHrf4UBSjHWBF2CaAKqazEZTO6ufK4Ej04Ok3OMVtzf+p2wCEr12id9DOxzO6d17ev/cA0snhmLWuj6bQprdDjsRBvDlyG/fcpbSh5AAbIj/hPYZs8x7L54sbBq0klwcdKAJuVvsJaQolgIqwy4I=,iv:WqzbV2s4y2FD0ENCnox3AcLN8ep2F0L1LBpazEBWS0k=,tag:WwVYS5p2/AGJeH4Pc5jzLA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
