apiVersion: v1
kind: Secret
metadata:
    name: harbor-secrets
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:sTilWbpOJAK98U4/ZhjWGgFpM+pWwkO8hQGqHSp47g8VXeWP,iv:/GeZ/JVpKc0lVM9g79praae3YMDJidfBIxJ+I39T/nI=,tag:TCzcm5mDVwgbFljjehB/ew==,type:str]
    secret: ENC[AES256_GCM,data:nWt3cOuQ64JxOrwF1Odfxw==,iv:hEaExwYofTMcE03APT88kXGIAZQZHPTYyy66AZz1ebU=,tag:yQN3RtXmA0SwHCQzwycRpg==,type:str]
    CSRF_KEY: ENC[AES256_GCM,data:lCCh/ESmw+Dssbv4+/J9iT8Ra6tM2S23ldFYdbV2Xfk=,iv:9rOvK947FYgZVpRIqLgziW+Xeek90Jq3UzKWQIOmw0M=,tag:1MUEKtInLHt2TZYpiIcyaw==,type:str]
    JOBSERVICE_SECRET: ENC[AES256_GCM,data:6FG/X0C/ZqA+w/1wKnr2Zw==,iv:DZfrjvEhsS8v3wcGEonZcGD2pyNz/fdRtR/B0VOQKoM=,tag:yzQ7L9ME6nehpy5cUyf9eA==,type:str]
    REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:obgG89/M4lk0Z7BBdaUL/w==,iv:9FMgwM5ZTxKy58KeE9Tau7bs7QNKejGXLuTiVRmARKY=,tag:7DF3gqm0Qxjkq0UEzyC1qw==,type:str]
    REGISTRY_PASSWD: ENC[AES256_GCM,data:ntMBZQI3Q0L10xpHPIbCGHTArPax2Sa0,iv:vooJTZjXHP9Esd18vxTossj5lssNPUWcJFgbu/tN/0Q=,tag:ui7HcA8A16ZuwYEji78v+Q==,type:str]
    REGISTRY_HTPASSWD: ENC[AES256_GCM,data:3xnGWNeqLt0w6J1ujyK8viEKewjwJJ/YAi1CAvDncc1v/CbnDzPqCDHguMRo8yzPCL8GFBYCr2I8H0qwTw7ryUt9yw33YFmePU3HTqMAmv8=,iv:vt6T74H86h1eSysxH7VLhDfZM7mTsoHUan6Rspc6cFM=,tag:yOFzqvCebRZVlyJKcBytQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ2Y0VnFzRUdTUzl6WDY0
            dTZPWC96bmFxMGdOTXF1UlhxL08wNWNSRVY0CkQweUlqV1FKaEU4SnNGVWhVTHM4
            bzJENVduTUhVWWhsYStiWFRTdTJtUUEKLS0tIHE1RkMxVG9ZcnBrckZGOTdFVUs1
            dlpIdVB5WmI3TmJ0ZEhjbWh3S2ZwOUUKavkBv0IY/DfVo4lSrNGEVavBEhzJS5D7
            CQWgcTX3BcSCjTiiv1xlc5aBSDsRLnl2ae4IwqKGQh4mu22mGyyGlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
    lastmodified: "2026-09-25T00:47:00Z"
    mac: ENC[AES256_GCM,data:YMB1Vf+obdq8Tu0VDzlLXgr5wf8/tO3P/1RzlIhv1ZQH4Wk6zg47pVUBYOyDM1vg9bkx13Pciy5I0xG5WCCXv6YT5Rm874oNpxzyST1yTnhxSoDIosnxkfQ6rPLRLnwHhsSEy8faCii5SqlI4HcaVanTFsUKGEYKvoErSzyi9sA=,iv:ONVmLTNE88X34ErL2U5XwTfB6bTRySMTfrCbVvtEqUw=,tag:/lU+PoxIAPNc2nz/VGHQkw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
