---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: netdata
spec:
  scrape_interval: 60s
  staticConfigs:
    - targets:
        - 192.168.10.1:19999
  path: /api/v1/allmetrics
  params:
    format:
      - prometheus
  scheme: http
