---
resources:
  limits:
    nvidia.com/gpu: "1"
    memory: 16Gi
  requests:
    nvidia.com/gpu: "1"
    cpu: "1"
    memory: 1Gi
# servingEngineSpec:
#   modelSpec:
#     - name: qwen-2-5-7b-heretic
#       repository: harbor.yanello.net/docker/vllm/vllm-openai
#       tag: v0.9.2
#       modelURL: "/models/qwen-2.5-7b-heretic"
#       replicaCount: 1
#       requestCPU: "1"
#       requestMemory: "12Gi"
#       requestGPU: 1
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - marcus-server
#       vllmConfig:
#         maxModelLen: 8192
#         gpuMemoryUtilization: 0.7
#       extraVolumes:
#         - name: model-storage
#           persistentVolumeClaim:
#             claimName: vllm-model-storage
#       extraVolumeMounts:
#         - name: model-storage
#           mountPath: /models
