---
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - marcus-server
resources:
  limits:
    nvidia.com/gpu: "1"
    memory: 16Gi
  requests:
    nvidia.com/gpu: "1"
    cpu: "1"
    memory: 1Gi

servingEngineSpec:
  modelSpec:
    - name: qwen-2-5-7b-heretic
      repository: lmcache/vllm-openai
      tag: latest
      modelURL: "/models/qwen-2.5-7b-heretic"
      replicaCount: 1
      requestCPU: "1"
      requestMemory: "16Gi"
      requestGPU: 1
      extraVolumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: vllm-model-storage
      extraVolumeMounts:
        - name: model-storage
          mountPath: /models
