---
apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
stringData: ENC[AES256_GCM,data:mHEnsH/YDbLVVU3i6eTV56NVuoGYQXVaDyqhqHd1fmUIOt/R1ngZyYtaZl/mSis4t4EMMvTi3SA2nGkwj6qXHaxjJuxwhVx2h0dvkAoRqc18Vm57avuXHnOx9gVnHi/vh3V38XuvnXYnl40YGtwaOQPCUXgMgo3ofoawdS4eBOH+7d3oKMj8zybz59vafuFabZa59s56x2BRKK+EGhAN1tApzXDj6z7GOzOhRLXvCJoveR7x/pRr9t4CVMDA4DWM5Y7Jtv3r75W6ig3W2rJQYttIJSFpPaAgiMlI3PgkkX8YRmOzD8VqYD4f/0RaM4GtTOcRb1WHXEhNiK/xJbBb3nl20FBqTENrT80U2ebkDcx4jv0hZK/6A4FtGEf/OWG9+nKrNboxeFN+prIdcuyi3Zu/POkLna1Q+8JANxuRjByuTerW+yCyLjJPCmi3SyN31r9aZBlZYzlLfcCCxUjvMfocD1g36G2J32O5sCoYYrFfhPVLlm4+U1wLlPn4ConBURzl+smAVzHeBjvvdvtRKL5b4H7/RYrw1VzvZ/TVhuDiSjxgUQlfLdX+MySp4KwqfHsRgRYmQGF6LwQlOAbd7DoWEFLu3DutKIc65m7T8NF3A1aqy08sLN19gRNF+FZO7E1zyx+uzqMhKiCAnmVBGn3swpcIu7yTyG41uecJRjzvF/Q5+cpulH5BEil32vkwsRasMVEVOutfIjUB0Ksu88EzNmw4a74hngI6Uk+05wtSc8wigbWLl4cj2oXugELzZ3XM01bViuM0GOmeX17L6Ql3ARjuIU7nrrSGnFIcxx3DpnYrm2fBOFWxx/aZk3YFP0xh0uh/SGAw0Yo2E1PBa0PU5TAeW0ERJdtLywizbIS7bBf8OsXfbgEjE96ZYg2KSt4K5r5hzqz7WUzVaquezMQ8,iv:uorFEfBG+RY8VC494wtgMPWGLwbQIuedVFVokVOJPiU=,tag:mv/yDOHGI64VFxX0SIH+vA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-06-23T17:28:31Z"
  mac: ENC[AES256_GCM,data:Bi/dyxn7AZwq92kmaazg8eA+mGoW8KOCagEhtqFcd8qZVzWzkKHawoeDAh/PvJ8Jj9bzILUgI0b/7Bxm6vr7r2VynWSwnWNvo3p3O8dTl3G8GAmHQFgnCUAz4p/3EI+EDM6xCoxjVXxYhy+KUhTXa5x+DicLorHsYRXqp5Frrd8=,iv:J3vSfFrVeIOXKtgMj6klcwJoD1ANqI//9auy/g7/7ek=,tag:BBnFadkqFYVlYvd9V9cG1A==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
