[project]
name = "wan-exporter"
version = "0.4.4"
authors = [
    { name = "Marcus Yanello", email = "marcus@yanello.net" }
]

requires-python = ">=3.14"
dependencies = [
    "cryptography",
    "prometheus_client"
]

[tool.uv]
package = false

[tool.basedpyright]
reportAny = false
reportExplicitAny = false
