{
 "title": "Power",
 "time": { "from": "now-16d/M+16d", "to": "now" },
 "templating": {
  "list": [
   { "name": "electricityCost", "query": "0.13" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Peak Power Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(iota_House_Watts_value)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "iota_Mains_Watts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(iota_Mains_Watts_value[1h]) / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "avg_over_time(iota_Mains_Watts_value[$__interval]) * $electricityCost / 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "iota_Mains_Watts",
     "query": "SELECT integral(\"value\", 1h)*$electricityCost/1000 FROM \"autogen\".\"iota_Mains_Watts\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(iota_Pool_Watts_value[1h:1h]) * 0.13 / 1000",
     "legendFormat": "Pool"
    },
    {
     "expr": "sum_over_time(iota_Car_Watts_value[1h:1h]) * 0.13 / 1000",
     "legendFormat": "Car"
    },
    {
     "expr": "sum_over_time(iota_Upstair_Office_Watts_value[1h:1h]) * 0.13 / 1000",
     "legendFormat": "Camille Office"
    },
    {
     "expr": "sum_over_time(iota_Office_Watts_value[1h:1h]) * 0.13 / 1000",
     "legendFormat": "Marcus Office"
    },
    {
     "expr": "sum_over_time(iota_Guest_Rooms_Watts_value[1h:1h]) * 0.13 / 1000",
     "legendFormat": "Server"
    },
    {
     "expr": "sum_over_time(iota_Living_Room_Watts_value[1h:1h]) * 0.13 / 1000",
     "legendFormat": "Living Room"
    },
    {
     "expr": "sum_over_time(iota_Breakfast_and_Dining_Watts_value[1h:1h]) * 0.13 / 1000",
     "legendFormat": "Aquarium"
    },
    {
     "expr": "sum_over_time(iota_Other_Usage_Watts_value[1h:1h]) * 0.13 / 1000",
     "legendFormat": "Other Usage"
    }
   ]
  },
  {
   "title": "Wattage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "iota_Mains_Watts_value", "legendFormat": "Total" },
    { "expr": "iota_Car_Watts_value", "legendFormat": "Car" },
    { "expr": "iota_House_Watts_value", "legendFormat": "House" },
    { "expr": "iota_Pool_Watts_value", "legendFormat": "Pool" }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "increase(iota_Mains_Watts_value[1d]) * 0.126 / 1000",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(iota_Pool_Watts_value[1d]) * 0.13 / 1000",
     "legendFormat": "Pool"
    },
    {
     "expr": "increase(iota_Car_Watts_value[1d]) * 0.13 / 1000",
     "legendFormat": "Car"
    },
    {
     "expr": "increase(iota_Upstair_Office_Watts_value[1d]) * 0.13 / 1000",
     "legendFormat": "Upstairs Office"
    },
    {
     "expr": "increase(iota_Office_Watts_value[1d]) * 0.13 / 1000",
     "legendFormat": "Downstairs Office"
    },
    {
     "expr": "increase(iota_Guest_Rooms_Watts_value[1h]) * 0.13 / 1000",
     "legendFormat": "Guest Rooms"
    },
    {
     "expr": "increase(iota_Upstair_Office_Watts_value[1d]) * 0.13 / 1000 + increase(iota_Office_Watts_value[1d]) * 0.13 / 1000 + increase(iota_Guest_Rooms_Watts_value[1d]) * 0.13 / 1000",
     "legendFormat": "Offices"
    }
   ]
  },
  {
   "title": "Weekly Cost",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "Pool",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "iota_Mains_Watts",
     "query": "SELECT integral(\"value\", 1h)*0.13/1000 FROM \"autogen\".\"iota_Pool_Watts\" WHERE $timeFilter GROUP BY time(1w)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ]
    },
    {
     "alias": "Car",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "iota_Mains_Watts",
     "query": "SELECT integral(\"value\", 1h)*0.13/1000 FROM \"autogen\".\"iota_Car_Watts\" WHERE $timeFilter GROUP BY time(1w)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ]
    },
    {
     "expression": "${Up Office} + ${Down Office} + ${Guest Rooms}",
     "type": "math"
    }
   ]
  }
 ]
}