---
defaultSettings:
  defaultDataPath: "/app/longhorn/"
  defaultReplicaCount: "3"
  defaultDataLocality: "best-effort"
  taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"

defaultBackupStore:
  backupTarget: "s3://myanello-longhorn@s3.us-west-004/"
  backupTargetCredentialSecret: "s3-secrets"

preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClassReplicaCount: "2"
  defaultDataLocality: best-effort

global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
longhornManager:
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
    limits:
      memory: 448Mi
  initContainer:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
longhornCsiPlugin:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 32Mi
csi:
  attacher:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi
  provisioner:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi
  resizer:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi
  snapshotter:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi
longhornDriverDeployer:
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      memory: 16Mi
  initContainer:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
longhornUi:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi
