---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honcho-api
  template:
    metadata:
      labels:
        app: honcho-api
    spec:
      initContainers:
        - name: db-migrate
          image: harbor.yanello.net/library/honcho:v3.0.10@sha256:febba9a2b119e7f7f12f84f7929ab3d788f2271bbb164ad27bd24f146d28d48c
          command: ["/app/.venv/bin/python", "scripts/provision_db.py"]
          envFrom:
            - secretRef:
                name: honcho-env
      containers:
        - name: api
          image: harbor.yanello.net/library/honcho:v3.0.10@sha256:febba9a2b119e7f7f12f84f7929ab3d788f2271bbb164ad27bd24f146d28d48c
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - secretRef:
                name: honcho-env
            - configMapRef:
                name: honcho-config
          resources:
            requests:
              cpu: 20m
              memory: 512Mi
            limits:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: honcho-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: honcho-api
