---
apiVersion: v1
kind: ConfigMap
metadata:
  name: honcho-config
data:
  CACHE_URL: "redis://redis:6379/0?suppress=true"
  CACHE_ENABLED: "true"
  METRICS_ENABLED: "false"
  AUTH_USE_AUTH: "true"
  LLM_VLLM_BASE_URL: "https://api.inference.wandb.ai/v1"
  LLM_EMBEDDING_BASE_URL: "https://openrouter.ai/api/v1"
  EMBEDDING_MODEL_CONFIG__TRANSPORT: "openai"
  EMBEDDING_MODEL_CONFIG__MODEL: "openai/text-embedding-3-small"
  EMBEDDING_MODEL_CONFIG__OVERRIDES__BASE_URL: "https://openrouter.ai/api/v1"
  DERIVER_MODEL_CONFIG__TRANSPORT: "openai"
  DERIVER_MODEL_CONFIG__MODEL: "deepseek/deepseek-v4-flash"
  DERIVER_MODEL_CONFIG__OVERRIDES__BASE_URL: "https://api.inference.wandb.ai/v1"
  DIALECTIC_LEVELS__minimal__MODEL_CONFIG__TRANSPORT: "openai"
  DIALECTIC_LEVELS__minimal__MODEL_CONFIG__MODEL: "deepseek/deepseek-v4-flash"
  DIALECTIC_LEVELS__minimal__MODEL_CONFIG__OVERRIDES__BASE_URL: "https://api.inference.wandb.ai/v1"
  DIALECTIC_LEVELS__low__MODEL_CONFIG__TRANSPORT: "openai"
  DIALECTIC_LEVELS__low__MODEL_CONFIG__MODEL: "deepseek/deepseek-v4-flash"
  DIALECTIC_LEVELS__low__MODEL_CONFIG__OVERRIDES__BASE_URL: "https://api.inference.wandb.ai/v1"
  DIALECTIC_LEVELS__medium__MODEL_CONFIG__TRANSPORT: "openai"
  DIALECTIC_LEVELS__medium__MODEL_CONFIG__MODEL: "deepseek/deepseek-v4-flash"
  DIALECTIC_LEVELS__medium__MODEL_CONFIG__OVERRIDES__BASE_URL: "https://api.inference.wandb.ai/v1"
  DIALECTIC_LEVELS__high__MODEL_CONFIG__TRANSPORT: "openai"
  DIALECTIC_LEVELS__high__MODEL_CONFIG__MODEL: "deepseek/deepseek-v4-flash"
  DIALECTIC_LEVELS__high__MODEL_CONFIG__OVERRIDES__BASE_URL: "https://api.inference.wandb.ai/v1"
  DIALECTIC_LEVELS__max__MODEL_CONFIG__TRANSPORT: "openai"
  DIALECTIC_LEVELS__max__MODEL_CONFIG__MODEL: "deepseek/deepseek-v4-flash"
  DIALECTIC_LEVELS__max__MODEL_CONFIG__OVERRIDES__BASE_URL: "https://api.inference.wandb.ai/v1"
  SUMMARY_MODEL_CONFIG__TRANSPORT: "openai"
  SUMMARY_MODEL_CONFIG__MODEL: "deepseek/deepseek-v4-flash"
  SUMMARY_MODEL_CONFIG__OVERRIDES__BASE_URL: "https://api.inference.wandb.ai/v1"
  DREAM_DEDUCTION_MODEL_CONFIG__TRANSPORT: "openai"
  DREAM_DEDUCTION_MODEL_CONFIG__MODEL: "deepseek/deepseek-v4-flash"
  DREAM_DEDUCTION_MODEL_CONFIG__OVERRIDES__BASE_URL: "https://api.inference.wandb.ai/v1"
  DREAM_INDUCTION_MODEL_CONFIG__TRANSPORT: "openai"
  DREAM_INDUCTION_MODEL_CONFIG__MODEL: "deepseek/deepseek-v4-flash"
  DREAM_INDUCTION_MODEL_CONFIG__OVERRIDES__BASE_URL: "https://api.inference.wandb.ai/v1"
