---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deriver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honcho-deriver
  template:
    metadata:
      labels:
        app: honcho-deriver
    spec:
      initContainers:
        - name: db-migrate
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
          image: harbor.yanello.net/ghcr/plastic-labs/honcho:v3.2.1
          command: ["/app/.venv/bin/python", "scripts/provision_db.py"]
          envFrom:
            - secretRef:
                name: honcho-env
      containers:
        - name: deriver
          image: harbor.yanello.net/ghcr/plastic-labs/honcho:v3.2.1
          imagePullPolicy: Always
          command: ["/app/.venv/bin/python", "-m", "src.deriver"]
          envFrom:
            - secretRef:
                name: honcho-env
            - configMapRef:
                name: honcho-config
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              memory: 512Mi
