---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deriver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honcho-deriver
  template:
    metadata:
      labels:
        app: honcho-deriver
    spec:
      initContainers:
        - name: db-migrate
          image: harbor.yanello.net/library/honcho:v3.0.10@sha256:fb443067febe9d82aefd2a490c919d01fc31ebbb50042e8dc5d5cdb75c790c85
          command: ["/app/.venv/bin/python", "scripts/provision_db.py"]
          envFrom:
            - secretRef:
                name: honcho-env
      containers:
        - name: deriver
          image: harbor.yanello.net/library/honcho:v3.0.10@sha256:fb443067febe9d82aefd2a490c919d01fc31ebbb50042e8dc5d5cdb75c790c85
          imagePullPolicy: Always
          command: ["/app/.venv/bin/python", "-m", "src.deriver"]
          envFrom:
            - secretRef:
                name: honcho-env
            - configMapRef:
                name: honcho-config
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              memory: 512Mi
