---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml

resources:
  - cnpg.yaml
  - redis.yaml
  - api.yaml
  - deriver.yaml
  - http-route.yaml
  - cm.yaml
  # - netpol.yaml
