apiVersion: v1
kind: Secret
metadata:
    name: dawarich-db-credentials
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:neuLh9zMXmM=,iv:Bzy+al0k8at77yrHyfBLVsesmyAdsQI5beJKeAnF6Uc=,tag:0OpTA5tjGvBxRz/qPCIN2g==,type:str]
    password: ENC[AES256_GCM,data:S3wVyknaC1t2m6gUvhaM+fE8XHXsfwBa,iv:Ndqe04BIjUOdLLtLCLdE4cA2lHDRjZrRtPF7Awe1Wro=,tag:6w9i8dx1Ibea9rm+X8saEA==,type:str]
sops:
    age:
        - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T14:25:07Z"
    mac: ENC[AES256_GCM,data:rmNVDCTNpe44lbJ8fUU+YyY7+RyKER5SfOlA0yzvGeXhp0kd1f/WyIUn9bzBfOvRWWKmc3+gWuJ/wH3NUe0h7dkUkL7RVARwtiTUTjXQQntb+xmku+AHYORqj9XIi6l5REi0Dt3Io8++n1pPbVVPAbmQSUIZ2nisyucm/t9c/Ng=,iv:nN7z8IaQySB5G4Gssrw/+n1SYG0UZibkcGOQs5pOJhE=,tag:pLc2+VjFe7aZ1/eZxfLaMw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
