---
apiVersion: v1
kind: Secret
metadata:
  name: dawarich-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:dmwVUBdYHaNXoo1dVIMz9imLW5MV23mxotpXhtBx9XoJax7e,iv:NRYVje7v7lahhSIF5oo+5Jqe7+H6ucXa3XKpQyR6vgw=,tag:mayArcIBDvhP4+mDh3T56Q==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:0/vuMVma5YjQJ05OWuOuNuhcPxrEaa7SB9kf1VtIxy/A6nUyQnucfg==,iv:ejkG0z9GpalEv9C9/tKe4HSn3Qn4fosWfcLkDo7zRrI=,tag:jvwh3AmCsnCxSDd9WTbTfA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Se6FOGmkpo1xeztRdctMvI0x74mJvEIBY6+V1wW3LlNyJ6ShrknyqN+j3JZYilJnPIwa7dc8d8JMr1Kqz4g74T7pTL1NC8A4+D8VhPpVv4QuUy16iIr4mHYQoTnTesi01hP4ktXYczqkeoZC87kruGT7MUd5B5AmkOUT5HndUS8=,iv:BSB/zRIoeiulJQFHThwzOhlePWUJufafg8Q7n8CeUaM=,tag:r2MxvFS7cpJ5rjDf3CUUuw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-07-18T13:44:36Z"
  mac: ENC[AES256_GCM,data:T34TTTJKUVjdEv0MDaRYa21WLzbIWAKrL7rDDoZnaiK7siJjfqa5mZPBBfw2LtXjKAnx8msDSgNBH2ZJOuDlGk8HMM6tWfEHz/Pw8MPUywtAQ942eNMxvTU8AOAtEAWgOi/TorAz2zJM0LNfMGvsyhxQf6AZ3qoDViL9rUxo4JM=,iv:/Zqe3b7KwDuxZJWbrl+SpGZLNV0xRs6y+FbWTqmredY=,tag:vpQ50pCOhjkeSCLh3Psb/g==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.2
