---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tracearr-db
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: timescaledb
    major: 18
  storage:
    size: 10Gi
    storageClass: truenas-ssd
  postgresql:
    shared_preload_libraries:
      - timescaledb
    parameters:
      timescaledb.license: "timescale"
      timescaledb.max_tuples_decompressed_per_dml_transaction: "0"
      max_locks_per_transaction: "4096"
      timescaledb.telemetry_level: "off"
      max_connections: "100"
      shared_buffers: "512MB"
  bootstrap:
    initdb:
      database: tracearr
      owner: tracearr
  enableSuperuserAccess: true
  superuserSecret:
    name: tracearr-superuser
  podTemplate:
    metadata:
      annotations:
        backup.velerio.io/backup-volumes: pgdata
