---
apiVersion: v1
kind: Secret
metadata:
  name: tracearr-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:qKTTwlSvYZ2TcZrAukyeYOvHVoEJTWAiT+g+4ii6RYQg2ZckZ05wM6HhjkuUb7g1,iv:4EjuhxzSAII/A04TRYW6ClZsS5JPBarfEFMNtfIUWQo=,tag:6RK+OfPWDzP8mo2cvbsSeg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:elT7q8mGTBDtGsZk+l0MNpr5KzPixVCcdGUL2xsdyBT5Pd2eqy5xo3LwAn/lcJV+somBB+f1A86MKjBa8UxWSNkQ10DJZsfLWT2cwtJP1FHeSDfhZw==,iv:qTMaqnGQ870bFaMTAZ/4D5YFAOpHYBfhSHbE/6VNaBw=,tag:WlXlDY+1JztIphUJfOF8cQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:KNdIHoNLdWiseUi/vLTO4fftNdBjNYJU1HNU+72QqRlNx/qDtyZc5HWKfIbZRrpE,iv:7csS7SwVIEaaXjOKa0S/sbP/R0mH9UxVVK+yb21ZVHY=,tag:fjT4u0EXr6hhReRg65OK8Q==,type:str]
  COOKIE_SECRET: ENC[AES256_GCM,data:dylOviduT+b2hFparIOt/VJfJpza3VaK/vUufB+dtSJx5z7GogzCUYhw8Wji2kF6,iv:3zUGICfh7Fd8x/fsC0Qr92CDwd5K6J0lgjCQOYqDOJo=,tag:an2D/f2o3OftbwE5TPqwow==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T02:24:33Z"
  mac: ENC[AES256_GCM,data:bn7uWy/8Q1ufu4wDR7ivmrG1kQ0/FNgH4mMttJtkkB4Od6v1WP9YbCNq4jxezk5oZ3CGZJ7UztF7FXoD3grn+ziQcmtAN3wCZs/r2KklG10aOkAwxXE7slda+SDvuI8Klcftvzf7vIrGCT3cZZod53WbOg3q4HBukhrYPVlHh38=,iv:IEx1Ge1johy7Snp3N17fMI8bowsCckcSwyz0b2ZM/TQ=,tag:PFSQLHimB9ytZ2Ak1IP1/g==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.12.2
