---
apiVersion: v1
kind: Secret
metadata:
  name: tracearr-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:qKTTwlSvYZ2TcZrAukyeYOvHVoEJTWAiT+g+4ii6RYQg2ZckZ05wM6HhjkuUb7g1,iv:4EjuhxzSAII/A04TRYW6ClZsS5JPBarfEFMNtfIUWQo=,tag:6RK+OfPWDzP8mo2cvbsSeg==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T01:53:06Z"
  mac: ENC[AES256_GCM,data:ooOWyZqFr+wjF2CDJrJJk0op+ZTslcearmU7t+H/pgsbf8GZEH+rg1Y5t0IHCVRnHO4+JYMdi9vtq3brGihwD4ueULBwIoDehjgdKU1/TP71Xx6kI+1MdU58X8FyGuHZCPZE4gECDajkOTUcT7dbyDlvbHvGNoY+1theEBcwqGU=,iv:xuKxOpcAay1F0uiIXYe/sAQKbEQ6GQGnaHw4FM5jdJs=,tag:COpmbqTyhLXZAFofhiSSMw==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.12.2
