---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:df+QQCgLmxDkfDRNisZjCU9MVZwT1qLDSXcOXrAn72W+NamBCkQT1WszfkJ/YXKDSmnbdKUx2aYJES30Bca36cRNQEjuWAU2256cnA==,iv:p9YscKxct/2/bo89/Y1pxSILkBt64MfQRphpZDFdwNY=,tag:aKZo/PGZcrRKdpJPKGmPeA==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:BuYHOa0TmpFnfquQGl6cHivRUbhJ1rvHCZXj4aynLqxcpss6LbY8Zfk1F87chYmq,iv:5ys+qT28fWsWnums2MZXagBDnCGFVLZhQP7uE26E23E=,tag:4fI/A6YqlizC/fsebY7eDA==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:AvyTMdrYuWpy5dLlvKKAi8QbvKOAQl+/dCi13889BEaqCYn8W0ek43HvsD3q8xGI,iv:aiZwVvURz988OaobiJ2UWnh1BYqnqL93SzaTUo+x07o=,tag:6Wu0l/q52PW3mBnTlPnYxg==,type:str]
  AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:SsGKzZo4lN5KG2BIaIt01KPs4CCE7g1vBbKBNqW5javhU1EBlwRkYZtgsuot4SZiRAZ7FI+Mp69uEyqSg4okJlAbUYAn18tKzkk3Fg==,iv:NXT9nBKCet7sKgorlxgDERgdHnLfxTHCKlHk6ar4TGE=,tag:enpRIjinDV5KQKFp3yuV6Q==,type:str]
  AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:v2aU5djsQ7ed8r9j3aYSzQ==,iv:XjIMmwxLOoVpOCrEFNdQ4rm2M0PSLa2NupRI3BTVKlQ=,tag:88C3Lq/OwKS36/O/UpD5Lw==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T16:18:44Z"
  mac: ENC[AES256_GCM,data:WqDFi36XS58U109u4c/xmIRtkxh5dRCh5OBZbnrma2sB2Ru44MYtQ9wn4DuubDOIaMVGndPbp6iveCyAOeIKpzjL3PVoKX/LLq4G/+PkHQxUtcf530nrx1KJBTSf6BjuvqGo52CK7VqvZFnG8UkKWMbuJlFX7FVLw/tkoNr0URU=,iv:rD75IuNqTNHjBuGDttewZ81dfwecn00KSFgi68Qqye0=,tag:IOpAx3pgkR7dxrWMV/z24Q==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.12.2
