---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profilarr
  labels:
    app: profilarr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: profilarr
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: profilarr
    spec:
      initContainers:
        - name: wait-for-parser
          image: busybox:1.38@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
          command:
            - sh
            - -c
            - |
              until nc -z parser 5000; do
                echo "Waiting for parser..."
                sleep 2
              done
      containers:
        - env:
            - name: PUID
              value: "3000"
            - name: PGID
              value: "3000"
            - name: TZ
              value: America/Chicago
            - name: PARSER_HOST
              value: parser
            - name: PARSER_PORT
              value: "5000"
            - name: ORIGIN
              value: https://profilarr.yanello.net
            - name: AUTH
              value: OIDC
          envFrom:
            - secretRef:
                name: profilarr-secrets
          image: harbor.yanello.net/ghcr/dictionarry-hub/profilarr:2.0.2@sha256:9a597204eccb60289e1b287f33bbc74665af66b92ad31c6207e6df3886d205e4
          imagePullPolicy: IfNotPresent
          name: profilarr
          ports:
            - containerPort: 6868
              protocol: TCP
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
