---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  labels:
    app: parser
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
        - image: harbor.yanello.net/ghcr/dictionarry-hub/profilarr-parser:2.0.0@sha256:2d3094fed51b79fe4beee3fa596d4d47c0879370425194f0e0c5ace6c7dadd07
          imagePullPolicy: IfNotPresent
          name: parser
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
