---
apiVersion: v1
kind: Secret
metadata:
  name: profilarr-secrets
type: Opaque
stringData:
  OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:KsloT8jZ58b88G2Z7IWgxieobp9xwbV9aDpjbaIDHsrh61yXA232E+1R6doU958cz0WYJSXdeA+KBuPABHMzcZ8Q/5hqGMm/gDUzQKBln/5DEH8+Cjc=,iv:dVT/N9YhMtcNW6K5iHDB9ZKyWk1qkA9tGSLUI0OZY54=,tag:3Pl+yHoKH8zJgRDnADfz4w==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:+VJorGeYApREq21Xw8PMN42um8aSEz8d8nhX7uNu1IZaEYWAbHEuig==,iv:Lh1cgzoN6mrpjiRKB9OIkJXZft9eQIA4OIDtnr+Ogus=,tag:mP64MfYZR2I/2qm2g4bAFg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:G5/bSaC6V/rbUdX0iponFJim7O8cyNwCSIMpqUTLBJuwhj0ePv8QP0DBUz4eMT7t02Cj4TYzNG1thIZjYgFJrSOPmF1ukQ2OwncKqDcTo+1/Cr6ip7clKZuTnpRpGPp6DCkVzq0JlurreY1h4/0TUk6eTHeDAjLaRolE7JMLek4=,iv:Lv1iOqLFa7+C/a3sifbbrfJP5yp5m4wMUny5vHYgueo=,tag:NaG1Are8uH+cS68JD61OdA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-05-18T16:54:23Z"
  mac: ENC[AES256_GCM,data:KtWBuoYA89mkmeaKgyKRCqV1q4U0DuPrPDf1EU5YdT6Z6wsXUgMSn3gyh9pdK0a178x0oYtSYfK4hJ1MuGgY5LnIHEtMRlfUmuWh5wfRSVxr0OMELQ0sDr4kV2fekEeqfEV48FcL917X+7OXbg2FtyeM45kwjQwhBIRLAKEHD3k=,iv:yGtuKNzDNm4KXngjHzq94ITu36oj/u3z8hhMsW5tX04=,tag:xFXd9CjCRHt404M1THhvTA==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.0
