---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: chartdb
spec:
  endpointSelector:
    matchLabels:
      app: chartdb
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
  egressDeny:
    - toEntities:
        - world
