---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: warrior
spec:
  endpointSelector:
    matchLabels:
      app: warrior
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "8001"
              protocol: TCP
  egress:
    - toEntities:
        - world
