# need to be installed one at a time in order
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jqPathExpressions:
        - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
  destination:
    name: in-cluster
    namespace: manifests
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/myanello/homelab
    targetRevision: HEAD
    path: argocd/apps/infra/metallb