---
# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      value: "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade@sha256:20d6f22e7383bead1a48ad0838247080c5d5b28ac0f10dd2348ebe0a5466a043
  version: v1.36.1+k3s1
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  prepare:
    args:
      - prepare
      - server-plan
    image: rancher/k3s-upgrade@sha256:20d6f22e7383bead1a48ad0838247080c5d5b28ac0f10dd2348ebe0a5466a043
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade@sha256:20d6f22e7383bead1a48ad0838247080c5d5b28ac0f10dd2348ebe0a5466a043
  version: v1.36.1+k3s1
