# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      value: "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade@sha256:f57caed5a5f93b0145cedfbb0b6cf5c6ad11980293dfb9ed2ce23095397a7a61
  version: v1.33.4+k3s1
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade@sha256:f57caed5a5f93b0145cedfbb0b6cf5c6ad11980293dfb9ed2ce23095397a7a61
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade@sha256:f57caed5a5f93b0145cedfbb0b6cf5c6ad11980293dfb9ed2ce23095397a7a61
  version: v1.33.4+k3s1
