# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      value: "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade@sha256:7ff06686f9eee87ef4a42a68515826252159abd52c878054b629534d71cdcc78
  version: v1.34.3-rc7+k3s1
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade@sha256:7ff06686f9eee87ef4a42a68515826252159abd52c878054b629534d71cdcc78
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade@sha256:7ff06686f9eee87ef4a42a68515826252159abd52c878054b629534d71cdcc78
  version: v1.34.3-rc7+k3s1
