---
apiVersion: v1
kind: Secret
metadata:
  name: kuma-auth
  labels:
    app.kubernetes.io/part-of: monitoring
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:KmW2IbYl,iv:9TF0z5PZpS2UK4ljDNNTe+L8XewQWoIigj3a19dKrro=,tag:SRnKCXKJMliSkPuemlnmzQ==,type:str]
  password: ENC[AES256_GCM,data:66rJsOwbCbC0a8le,iv:Gd+4r4lNKCSKKVkW4+t3JTSLn4UEC9ZHBp2+1fAG8To=,tag:zMTqCTheJ6QfkcDn1SnCdA==,type:str]
  oracleApi: ENC[AES256_GCM,data:ZSMqLKCBcLPCNEcY2KASxWX296X6PB2IjVPlBTAqzXO2T5TYP4IL5+1lKtw=,iv:z7MaLMf50uXd+uX9+ttewkG6ZYNMiyS2hTi+9r+YEq8=,tag:GPAXdxryNfTrI/SxgEe25A==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T02:21:58Z"
  mac: ENC[AES256_GCM,data:bPCRgR3lkjy0kidAsbwaD72tzcL+UGC37nnZ8STF39crmHWX6x70EdQP0cqpPmqMR0uELsL63A5pjtNo6GnOyDsnHvjjY9Sl57s7QJbUrlbR6hzfZzHTKvnfuK7F/sbNvca5FaG9yBAOvTvyYKulxX9eYFi3AVIY0BSM2Q1tZT0=,iv:IXb16u556bPh9K2iAUyG9vYURHqdnVCOg/tNzvZ/VdI=,tag:1aUB/zRROMPUW50eVKR/lQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.12.1
