---
apiVersion: v1
kind: Secret
metadata:
  name: vmalertmanager-ntfy
  labels:
    app.kubernetes.io/part-of: monitoring
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:6WtMY7ooSal7Rj56vDULQ/62p+NxB9lWvAbTISuNiQ0=,iv:ngFfJC7bvZp4FWrnBCMi/AH5dLZSvqIoIPR/YhAcNSY=,tag:ScpDwddbcAZHTRBUanFOSA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRXhHQmI1RXROWVpnR21F
        UjM3NklRVW41NlFVcTd4T0xoQllxMzdDYURzCi8velFabEdMV1JWcWJCZmpobys5
        SlZNN0dtUWplOEtEUXliTS9mYVpxeDQKLS0tIHpXamtSdHlHMGpZS0JycmN2Qnk1
        NjlKYnRyaTdtTmdkL3BzQjZkRDRGNEUKTBdvsuEhZwzqbyRr/bUjaFSN3IgcGPlh
        STb17DfhAVQ4ywnovrJCCdZowQ1uKh/E1jEIr7P06sXdSWByW+odxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-10-02T00:07:33Z"
  mac: ENC[AES256_GCM,data:SRodjUwIgYPw/ZUk44MnIOuTUlBLj/QzWNXwIgYa1w6TRzWyWekWppwAftDDcTwEIlPIFJzCdvcDifVz/XoepyoO+J/zxRF3GZ/8VE6puFgmZgNAElAe6XkeuNQF01klmyW3VUvaMvrVk2MjlBKEe0OUpjgwe9WA5CQQWIXfSl4=,iv:GO9/GO9JuxtvLRwRHRol7GleSYhHnjXqNijVu3mx0y0=,tag:RyAAp4mDHJyf76ZLioh1DA==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
