---
apiVersion: v1
kind: Secret
metadata:
  name: truenas-token
  labels:
    app.kubernetes.io/part-of: monitoring
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:v66uZFc7MTuzu+WeKGxzxivh3UnfhfGeyPuSnRhavURUivn4fS0crAx+Wrj64Pz6zg0QUr+9P0F+Le72uVjJ/WLA,iv:XNEHk6y2hJ3y2Pw9pgKq1jW53Blz/ly81Hn6+HosmN8=,tag:PfNDPIdccyyDuE3TUXmtLg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-10-01T21:21:34Z"
  mac: ENC[AES256_GCM,data:j7yj7dxeMrpTbAeyM8KDdoxVDevayC0HGBiW8V3DavlWceTo1/mefTed/FDEDb7m4yu/FNQHiVFc5008ELhZrtSrGw0YwSNohSeyWOGcy3v+afZyJkg85TCUxBonOVNkJDPjtPKeS/bcxgdFbS5AKRwZJAQsG1jDL91ZyFop3BQ=,iv:6GAjZjZbAP9217NjuEcENfYh24W/17kwI1DXbyGBftI=,tag:vBSmSdYkQYVzdwRax59QCQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
