apiVersion: v1
kind: Secret
metadata:
    name: cross-seed-conf
type: Opaque
stringData:
    config.js: ENC[AES256_GCM,data:ldtOIylU+A7V7AFjXFkPI8qOpWqhv+ABoO73F4+CGwcQzFvY/YuqqDhMGxd+Wz/XxLkRtHj5WU1FGfkAt0o5xsqqW5twqWJHr0tY9uDb+TXiyMrF/tD8Uixjy3WQehRIlcBTP+3UYFd1XAq6QahcRHCyvBQO7kFsayRVQKqIaXLPIGKJpKWzXLCmFT+nGXS9mvS8yg5ouKoyBYopVBUycQf+8E64ugmlykTTsGk3vPOlhsIs3msSfPSDbLnTycy+WSjccWDwmEWyBvKNjxgwjehs8jLqPD5JoHJAtL7TeDvMuvWxgdvZIQV13O62HX66ZekWyz6YZksr11bv3z9WbWQhYRyhkv/6h1x4c7JxX7gF7i57jtYs+krjIhwHvXCzgEUPHwwWE5KTQNttlknJY8kXkvKFB3M5iJPvBqkEp9yC+fm9CE5FXpzQ4p97M9h9duqRla1fuSs08eYksRCbUBE6mE2/qFXoBXaX4Q0+2fCkNoF7bMt3CRKULhxeN47zEUBE1YrlOabgy/F2EEC3Q8+U97oSWXVY/ix1wK2IfvifMHqiQhw70dqalzj95sPkuPAdfOms0ei3b2kpIsIrIivDp4qFz2n3FGRiVyMbsbJf7zXS9jhl0OXlqyTTdJJeYDcAtWKUMWQbk4SEeGVndwiy+OtqQnq5n3WHGwyRgViN7yAPaP1D717YkDe0i9AwfFeWkBPfZz88AlpDHp6BUuPUOyPyyigqki12A5MXPxjodZHJsPIHwPuHS36+rJ67OEKYuodnUgMLkktnueOgoAw7hw==,iv:0ysks8kVXXyxp0t9+gOuyxqyQN4M9XLPTLgOKpLYMB0=,tag:zp6uBAs1WS9PulJYoNfwQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
    lastmodified: "2026-09-09T21:04:30Z"
    mac: ENC[AES256_GCM,data:rz/DGu9v2IJjq+npvfL6nq+vsAQD/MEeKoExIK25vBavB6/99ltAS7usKXcrgWlAk0F0Y+H47Nwcq1eH76Qj35dT8D0H4zd/Yoa2GI/sn6ya1ZSTQ1Laa9HNb7CDDswZp7QQHXDQoWAvXYCl+gFg6j32PCOodPccw1FUp7WT3Zs=,iv:JuR3L061EF9fwMhfSbmAPldKSr0Td8GJc/OU7w7zmj0=,tag:BJrB+yD6v0UI0/bBsWxptw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
