---
apiVersion: v1
kind: Secret
metadata:
  name: cross-seed-conf
type: Opaque
stringData:
  config.js: ENC[AES256_GCM,data:zq2tGFK1GZMk6PI5qUYy6IZ/Gh2Ebc0WNGMbgjAWk80SOl2WB6v2ZZZTrvliNn/LOcpqG5VIJrZTnhH4NCbx2TnD4ybSsCY+pCrIGAxsrwicbhrtBdTR9R8DZLEk6TSgwNAgTG2abH/kJlmm3TG4gAFQgQN+9LvteaoLH6W2dR7v2jqf1sdkB0WCmNBVCAOjT0jfpDADawxm093De1rEeg1I87fVHtYWqBNReGf8BgyppSemJxNPuWMJob3AzhyOU6xMA6VpO+7kudGS+qcwHJe7m4vgfjg0xPS7QJnTTwRNPYSY216jypdw6Wh7EJy+8ZM1SVhABgrtdDvQGpDYk2BGQ2kdLB7GOhXieS58Kieiwdz+5OW0h5D88xqtw1sw7y7+JUG33NfcFjb2XQ/MhZBNWET4ivcoKT/LP1EWfBzYkUpTxxCK8OyJIp53eRijBkuEW9xETkxpV/VPu5ySjbYwTVaMsNQvNwSjQ8pUvm89ga6MjSP05gl0/EcUTFsjgz0sgLVm+kdhcfYjOnFh1h+EvVIWJ2jOd0WnzlkE3orOwXU+8qyvWCfSXLopoRo+q6McCP6RZFGPI9w+BkAe3jHuDiHvhWtxhzY+C0Q74qWx7bCNMblVX6xJniQCCjFqsTUNsXsZBMrKQuM1Bmgy0lvowiHuP6fneatd6KaEsFKPTdq9TYD1k/AOdibNJnIq6yDzk4ralpo9X/OvB/j9Zgv2p97afij5g37OaWoQKTPhmdibgQ==,iv:zYPxALRJZ4Aps10vG9v3Ejwk3OhBmHNdy+r6e4XJLaE=,tag:fCO7Bp7CO7eUKbG5u7DMYw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-08-03T00:33:34Z"
  mac: ENC[AES256_GCM,data:z7NvFux1XRQ3R5BKZwUQmijPqqlXM+jvY4MgSErHzb5Ullb5yVDd1kpE2MXcaEck70BHp8wX/lNhMHtXecDon/SBIYLgNEvPuLZjogf4V0076ytGejjoD+EtsW3bMGEQHP3cfy1Sxlmr8mIrStY+29rm4xiCId8Af+7RPkYt5sk=,iv:7qea0KdEKIAQhI+7m9fZETHugsDdVB6db54kE/ArE8g=,tag:8Pe5lYW+y+U9jp6hBy7GFg==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
