---
apiVersion: v1
kind: Secret
metadata:
  name: cross-seed-conf
type: Opaque
stringData:
  config.js: ENC[AES256_GCM,data:mtO+2mL+cSfKpKBFWtA0CaFRX4bu3CPstCsqVc38n8fb1LgODKbL4zYnlAx9Ybxk9d1S39CO9RvrIcyIVNJqDqhhhOVxOUQ1+SJAlEMFDcJ+esKuAWfZxUdQvx0ZlXfztXpwBcIC9sS1vb7CPLHb6qUrLs4wNRaZ5SrLC7KF8OXvZugZ0KWN8yo1MYVCHcWlCNIpX+OSDHnXQ6U4jXycSPaLVTbRLn+IxPBuULF6g04jX3hEI9IcbBB343dpiVMz+UXHcXKVewNtFKAhXFVqH/BqZxeEsOWDA+C17gU3IclRQZFHajM1m93BtDzFw8UjsIZHudAEyGiaGcUi7F+evbGmt92QKX0pIqJW4dFjdDS0IsfxPmGHXNj9fMFRLkVdVQFbATRsT0Ec/wkrYNZDvgfBT8s7By3ANXHEghm7who36C5KYi1e17T6tM7HkSCnlAyHBimgw/7nef5sPV+vBBP3jIrpKZ02WZeJFQYeaODjXtzApgtPbeOeczFK0mzO7PZ8HED12Tj9+NyLxcHurzyw4A5JEVSCmMa/zoGUnoxd2KfeLc1FzLsUr9j5yFztlWhxhaDKeU0wWYfj1pNcuppN16gA3KVTB5mzGih/MUrAuUjK0X8=,iv:torMTGrWvmN2GuFdYWmn09b8S4ajOGCL9fE6qjVMloQ=,tag:UHTCZdHLtauui5UE89hzfQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-08-03T00:17:08Z"
  mac: ENC[AES256_GCM,data:e201QzpJRztiJpVnxkGXf5J9g/Ynq9PpwzGqHhLsybRzUdaGf1GWFWuWVTBHabhKPbATLggefySEbgTcheWoPsbUfEC8Cr0G/44JKYIQHl6L3nboWLxBvh4dj19xuXnykHzral8sXQwAOUNG6eU3JmW016NxmHJC/OXd8nBhsCc=,iv:EyIEJhiOif6VWGtOLmsq5giK01Ydm0jSkdp69eAzjTY=,tag:FVnrrYuNz2mXWYb/ZUvMKQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
