apiVersion: v1
kind: Secret
metadata:
    name: vpn-secrets
type: Opaque
stringData:
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:EZ3/ryT9T4NY/nSitA==,iv:xrba1nMSSwYPDPN+pfyDtqiBYOs5iqzbk5+lNjR/7vc=,tag:MoX+yz9cb4CcGa3nHXnHYg==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:8R42D68=,iv:pD88acUQAchMglljq0DWQhvPQLPxo/mdgTtKGOHtp3A=,tag:NeBFb0Ly3HCz3wHKLpun9w==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:CaRZ17/7W8nPgba+fN3tBm9fACT6b8pl8iMUpUHFu1WhPKQUs+8lq92koU8=,iv:0f821x11JwmZ70ZtocF6LDybW+QlrBFATshX6QtKXAM=,tag:72wuONilX+87vsX0lOHgUA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:xZe3/lzntlqp87mNm+BSi6eudEiz2IZyuyK0EgVRgrofQHHYYXbMzGXjKCw=,iv:9iGl+OncBzqgODLMnyZ0P34VM+wZwTHInOrhdCt0yAM=,tag:3VfG5RkCNi80WpjneSMF2w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:pxpGUGYJvHnqcgg=,iv:wnfjKS0QJJH6QBPyxAKu3detbss2s4Z+yxgYbecv+fk=,tag:MRip5hnbdF7aicK0A0acOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
    lastmodified: "2026-07-12T19:11:04Z"
    mac: ENC[AES256_GCM,data:hv0L8q+IdF/FAZ1u47No4d9MRC7Qc3LNbI0MoZMb7yXbX3+Ck59Xc6VQca1PZep/GQl2qATp75TT9Ip5x8YCyU8r5rq5ciI/YHaIUL+iNj/Ie5xxx1+L4yEG/3pZJMuunCCYbJCbTWuMrFzA0qO0SmQOn2GAKh8sUsQrUHUWRdg=,iv:UNGbVEqdLDeegk8CTQPmGh7mVBZA3BVPBjnSYcjFYnk=,tag:7hpOB9pHK/+S8YPeoh0Mew==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
