---
apiVersion: v1
kind: Secret
metadata:
  name: vpn-secrets
type: Opaque
stringData:
  WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:EZ3/ryT9T4NY/nSitA==,iv:xrba1nMSSwYPDPN+pfyDtqiBYOs5iqzbk5+lNjR/7vc=,tag:MoX+yz9cb4CcGa3nHXnHYg==,type:str]
  WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:8R42D68=,iv:pD88acUQAchMglljq0DWQhvPQLPxo/mdgTtKGOHtp3A=,tag:NeBFb0Ly3HCz3wHKLpun9w==,type:str]
  WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:CaRZ17/7W8nPgba+fN3tBm9fACT6b8pl8iMUpUHFu1WhPKQUs+8lq92koU8=,iv:0f821x11JwmZ70ZtocF6LDybW+QlrBFATshX6QtKXAM=,tag:72wuONilX+87vsX0lOHgUA==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:r5C7KliOyEHPiZ6JBCcKaNMfV9PdlQQ4nz9m7fwEVGTBTIG1NOaqAbLhpfU=,iv:kJIksDIm7u/BnMrpYImpV52BqMr8ekM0G4ScBXrP4V8=,tag:lMENR8whc7BgcTL2ca9HKQ==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:pxpGUGYJvHnqcgg=,iv:wnfjKS0QJJH6QBPyxAKu3detbss2s4Z+yxgYbecv+fk=,tag:MRip5hnbdF7aicK0A0acOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-08-22T17:43:25Z"
  mac: ENC[AES256_GCM,data:983AzitmV0AzcQSdzfWCnsjF1r2cSXMHvsZCRxaxet9XJ6y0eMlr4eMlb1jLv5xNKl5rp+V0ksq7qWRTNoobwPDyuTP8SINxzNzBuabbiatfCXtezOALt8sB2LLU0Lo8qX3NnttdElZ6XfAd+TJLIp11vJaqmm0D/rRyQyeFkAE=,iv:lOcjq3esONcR8pPW/9qqSg2qeojx8Bq7oSNAvFuEOaM=,tag:Z9jRaWub7Gf0R+ORgKNUnQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
