---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: bytestash
spec:
  endpointSelector:
    matchLabels:
      app: bytestash
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP
  egress:
    - toCIDR:
        - 10.10.8.0/22
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
