apiVersion: v1
kind: Secret
metadata:
    name: bytestash-secrets
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:uZ9JVHuhsuDy3zgbragIQz7trR4cP+OD+SuRKuf+e3iHAgao,iv:D/bJ3wolmOH5HuQ7oOr6gTrxJdxYIbora7zB4ePBD54=,tag:9RFvJl4rDGoK1kd8UAMgJw==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:cNyWNnKZ7QAp1cMqUeSCilrwmXlqDupNx9ikNaTeYd2KsaGU+XLsbw==,iv:OXQA6o/CVmwMhqgcfs4TFm+mw0K85+uX3afFQyWmXoA=,tag:I0NEj2Lm/6HfM5flvzyCEA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:vqrcvVduAlMJdE0+nxQl2lIvJEw19AMr3hobZJL/eiOYi4I+7W0AxCCa0rU3NxSymi5sasIwtzORAA580G/t+iWdXaZKe32kdk1tKZOjHf4AwTQ2uX4ECuyOTB7fYni3/nGY8KMqSBRgGZMPVMhS2uUE0rhbu4Tkd7JQxDVLDYA=,iv:U/Eqmy9dh53yVfIPGWX/d+SO8jD7TdWUg6wK/XfLpOA=,tag:ph08NDp1cBFQxTNHXvvKFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK0NWbkpIakZOSTlTWUts
            TnVIWmRJaTRwcUozdjZMM0FnclpUVDAyRFZVCjQ2eHd5aGdaSFRpSEtrc1RHaThV
            cnprNk53bXRJUFVHM2dLUUtxNEdNd2cKLS0tIEo1dm4weGdtNHNOdDl2aDcveHBL
            SnFSUHVQUlZIQjYyWmd4dis5ZFIwbmcK0Z6G7noV+pf0ZauT31yH95EpO4c/E/yk
            vbeJDjJCgZmJbtxZFReWkNGIw0kB/Z1b3xJBaRDl5uaxQ1u1UjToiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
    lastmodified: "2026-09-14T20:20:57Z"
    mac: ENC[AES256_GCM,data:wFe8fzAjIhk6c7ykuNM2lwBirhBNFtRJL1DIfmw4XdkePtMo9emqFHBlKOiwLhnt1pm0ntbbwBV6gf2klMGTWuw4x4V6N+NeQvvJx65lZZ9hcnXMnouAlFkWk37ztc/I4rdlWVFW/vRAXoW54Hu+GRB5R9uwYj6fxp9cMMp1A9E=,iv:QUY/qWztAifSK3Hi2pd4p38FCC0ZvgfMfMCUHo2w4rA=,tag:vDsxa5k3Lsr/qtDUsSWtOg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
