---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bytestash
  labels:
    app: bytestash
spec:
  replicas: 1
  serviceName: bytestash
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bytestash
  template:
    metadata:
      labels:
        app: bytestash
    spec:
      containers:
        - name: bytestash
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ALLOW_NEW_ACCOUNTS
              value: "true"
            - name: DEBUG
              value: "false"
            - name: DISABLE_ACCOUNTS
              value: "false"
            - name: DISABLE_INTERNAL_ACCOUNTS
              value: "false"
            - name: ALLOW_PASSWORD_CHANGES
              value: "true"
            - name: BASE_PATH
              value: ""
            - name: TOKEN_EXPIRY
              value: 24h
          envFrom:
            - secretRef:
                name: bytestash-secrets
          image: ghcr.io/jordan-dalby/bytestash:1.5.12@sha256:eb4f736b8cd45443be0ed6d8da3ee49b76dbf27f4d3925b81b3c407207e62531
          volumeMounts:
            - mountPath: /data/snippets
              name: snip
          resources:
            requests:
              cpu: 10m
              memory: 500Mi
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: snip
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: truenas-ssd
        resources:
          requests:
            storage: 5Gi
