---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: node-problem-detector
spec:
  endpointSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - node-problem-detector
  ingress: []
  egress:
    - toServices:
        - k8s:
            serviceName: kubernetes
            namespace: default
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
