---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bookorbit-db
spec:
  inheritedMetadata:
    annotations:
      backup.velero.io/backup-volumes: pgdata
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 18
  storage:
    size: 5Gi
    storageClass: truenas-ssd
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
  bootstrap:
    initdb:
      database: bookorbit
      owner: bookorbit
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector
        - CREATE EXTENSION IF NOT EXISTS pg_trgm
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
  enableSuperuserAccess: true
