---
apiVersion: v1
kind: Secret
metadata:
  name: bookorbit-secrets
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:IY3n6+xxZ3jb0tNVm14/bQ0LJ+GmKV1nR97v9hyWlPeO7wx85uzL/6cu7raMREOybhhGbqQOlvnxfLL1licg3w==,iv:8ZV723baTymf4BSxB7NHOuROW1rAplzwPSDJksGNe5M=,tag:z8jGeNwIekJ0P6UKHbG2hA==,type:str]
  SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:ezVE66mjAHs9ZCxvGNwbMvBNa6q64WSK5pWyASo1cbQ=,iv:yAYJIbvxYN4wGVhTzRKro/kf4JoVyAVjJhI2JAi9RqU=,tag:TZuPpjuDW72imJAnbyf6Dw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSStDM3VNVmFZVE84RlRj
        L1JxSGgyMHBoZGgxd2NIeHJzYWZ5OWJUU3hrCmV5bTdzWnoyQlI2NTlmY29maGZP
        dTYrTTdEWWlleHFnSWdEdVYza3Z6UzgKLS0tIFdCOTNBNWJpZlQ4T2RCamMxYk1Y
        eEIxVjdndnAyTzRJN0NrNnFlUENqcUUKqq293XLEB/DEo81iNe6fsNocmRTKHui/
        8V6QGYlZ9aiP3TpFmIS6J4Zgn4bTwTtWiWkiWKXRoLv20uih9XWZZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-05-30T14:17:11Z"
  mac: ENC[AES256_GCM,data:lRFAhy3qHaN2KdsWGEpwLwmY5NwDo4SJKd623BHJslw7SCX7z9YkKxoKg9MSO2lRiTW5tCOC3yQzwvyuubjc5+PXSTFRO55h2p/uqw7zGMmAvlcB9lh/OimQGjxDkD6d4qI46aiuASv7xCReUF0UsgpzYsLQ2EBSl0nkQiiSCPU=,iv:hqCslQq07GjeWVWK2ORuhRyujn55liN2Mh3OaVX1HaA=,tag:zDu5uKls5WuAEcG7XEc24g==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
