---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wan-exporter
  name: wan-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wan-exporter
  template:
    metadata:
      labels:
        app: wan-exporter
    spec:
      containers:
        - image: harbor.yanello.net/library/wan-exporter:v0.1.1
          name: wan-exporter
          imagePullPolicy: Always
          ports:
            - containerPort: 9101
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 16Mi
              cpu: 10m
