---
apiVersion: v1
kind: Secret
metadata:
  name: wan-exporter-secrets
type: Opaque
stringData:
  NTFY_TOPIC: ENC[AES256_GCM,data:QPBoQAzAKyYibzam18Wb8A==,iv:Xh0eaoM6zyJcDUNAiLZEjyw3QnIIiySYOGSeCsLbg30=,tag:RF0Ipmm9NOtMq+eFkCwdIw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-07-19T19:14:02Z"
  mac: ENC[AES256_GCM,data:pdYCZarhp411tCEYjExLvKfEYytIF7M1eerx4GJEkOmX8l4Li2n5M19k9Uaa4iNUwibxavQi+9WLZipPDTetGnFjy+c3nyREst3d9RgPhpxBJ/5GhTvb4PcAZpGtU0c6TK3gO8ivVIQYs0pYgUw4b+EGNSS1Gz+HgJhF2iTbCR4=,iv:6EeYOuVyCxR7EbFi5lxOdGhoraBAXjUMHdtMGPV9U04=,tag:sXIpzHIPNU2bF0TTFFQgOA==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.2
