---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epic-games
  labels:
    app: epic-games
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: epic-games
  template:
    metadata:
      labels:
        app: epic-games
    spec:
      containers:
        - name: epic-games
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
              name: http
          image: ghcr.io/claabs/epicgames-freegames-node:debian@sha256:b27f141d828f5003ea26f2483958afcee36d8515e64bf6b32217120a1546d4c9
          volumeMounts:
            - mountPath: /usr/app/config/config.json5
              name: config
              subPath: config
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 1m
              memory: 300Mi
      volumes:
        - name: config
          secret:
            secretName: epic-games-config
