---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: epic-games
spec:
  endpointSelector:
    matchLabels:
      app: epic-games
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "587"
              protocol: TCP
            - port: "465"
              protocol: TCP
