---
image:
  repository: harbor.yanello.net/ghcr/hargata/lubelogger
  tag: v1.7.0@sha256:01bdb486af71e641c3ae41499e0412a21f2e04fa31b25c5c6531b42c112938e5
config:
  userConfig:
    UseDarkMode: true
persistence:
  data:
    enabled: true
    storageClass: truenas-hdd-nfs
    accessMode: ReadWriteMany
secret:
  create: false
  name: lube-secrets
oidc:
  enabled: true
  name: lube-secrets
