---
image:
  repository: harbor.yanello.net/ghcr/hargata/lubelogger
  tag: v1.6.2@sha256:a289daf3670f49a8be4e7d4f8f88d6af3699e19d67cb5c6e4afc9c30777ec2d8
config:
  userConfig:
    UseDarkMode: true
persistence:
  data:
    enabled: true
    storageClass: truenas-hdd-nfs
    accessMode: ReadWriteMany
secret:
  create: false
  name: lube-secrets
oidc:
  enabled: true
  name: lube-secrets
