---
image:
  repository: harbor.yanello.net/ghcr/hargata/lubelogger
  tag: v1.6.2
config:
  userConfig:
    UseDarkMode: true
persistence:
  data:
    enabled: true
    storageClass: truenas-hdd-nfs
    accessMode: ReadWriteMany
secret:
  create: false
  name: lube-secrets
oidc:
  enabled: true
  name: lube-secrets
