---
apiVersion: v1
kind: Secret
metadata:
  name: hbox-secrets
type: Opaque
stringData:
  HBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:2mG4PUULjNbQqfiUJAp9l2z9eAhdvEVtlkrm7fveV5dQ7lu/BesErA==,iv:KkipwGkF/TE32QphRehB9APCVmDKi7Vu10j8FK7US9M=,tag:HCgZI8+xR+B+m7jXgHTrZQ==,type:str]
  HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:OxGpz/GnLtyuAAflwFPiZ/ZyzioPjfzSZdZDwWD33x3KV/kOVaP0UI05WHiCxKipZ2WX/DtJcSl9TcwLMBjqu+lnuAqPv7Y14eVrJdsU0BP+ZxLKhyubz0JIePK+5S1zSvu31OrCkcs8f767GDVyJFN3TNY5DrSXrrislVUUzGA=,iv:b2USwKX0CoHqbFk1Z4tF6zlppoH4TCvqG+CR7Cjlyn0=,tag:KHSkdU24SsAz4/Iaqb+/Iw==,type:str]
  HBOX_OIDC_ISSUER_URL: ENC[AES256_GCM,data:ngCLhaATdRSJE997C9BPzV5xTalMSO/M3dk/p/1yJOFFq6ybF7vdmvmQfFgNJ0k4YvyGfg==,iv:Qmp+M9D1atmf0fNg/NsaHZT3uvvjJSbc+I7Ushy9nVA=,tag:YBfdlgjPg1vjM/GdoxVS5Q==,type:str]
  HBOX_AUTH_API_KEY_PEPPER: ENC[AES256_GCM,data:Au4Ywb0j0aFoQ+EOjr+Uxhpn5/b9yz5THRf4PLCERqKmtjBZ8EKWQs+GhYKEZxzbvFseptD/Da7PshjJe9JuOw==,iv:dw9t+sdEei4IzPMvZ/cUhbnaqzph+OzCemWPn830SlM=,tag:vgvFMo0fv5FFj6FeA/xIVA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-06-21T20:50:53Z"
  mac: ENC[AES256_GCM,data:T1256d5DCVJ78n4xgSzhO5R7a68FWmFmDwk2a9+OCkeH3MmkwfJjqFociBXPTtlkkGAOUUYws2npYtbLsMZLY2EOGxtZT6vlUuEYwBGCAoXJg2+OdHu6ZkraCIFU/GhpLNhOfzuPdpBQOLe/o259/rcLhGMeM849K4sLMOiXwGc=,iv:SbPVpWVyfY5tlrd1vcK2ijBAJ3D0Tk7YAxkVdBDvFkw=,tag:zVlfvQeA2B/v6tF6gRha8w==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
