---
apiVersion: v1
kind: Secret
metadata:
  name: hbox-secrets
type: Opaque
stringData:
  HBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:2mG4PUULjNbQqfiUJAp9l2z9eAhdvEVtlkrm7fveV5dQ7lu/BesErA==,iv:KkipwGkF/TE32QphRehB9APCVmDKi7Vu10j8FK7US9M=,tag:HCgZI8+xR+B+m7jXgHTrZQ==,type:str]
  HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:OxGpz/GnLtyuAAflwFPiZ/ZyzioPjfzSZdZDwWD33x3KV/kOVaP0UI05WHiCxKipZ2WX/DtJcSl9TcwLMBjqu+lnuAqPv7Y14eVrJdsU0BP+ZxLKhyubz0JIePK+5S1zSvu31OrCkcs8f767GDVyJFN3TNY5DrSXrrislVUUzGA=,iv:b2USwKX0CoHqbFk1Z4tF6zlppoH4TCvqG+CR7Cjlyn0=,tag:KHSkdU24SsAz4/Iaqb+/Iw==,type:str]
  HBOX_OIDC_ISSUER_URL: ENC[AES256_GCM,data:ngCLhaATdRSJE997C9BPzV5xTalMSO/M3dk/p/1yJOFFq6ybF7vdmvmQfFgNJ0k4YvyGfg==,iv:Qmp+M9D1atmf0fNg/NsaHZT3uvvjJSbc+I7Ushy9nVA=,tag:YBfdlgjPg1vjM/GdoxVS5Q==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T21:15:28Z"
  mac: ENC[AES256_GCM,data:8JRurYICFfXToxncCSaLw+6ccdfvSpJrSMoyb+xLYdpjx/OggsfP1wQm8tI8PpCPIDgSu5VdMVKcoJ13hsD0FQUohIz3Z5p15hkMTphUfYWaCgo6RVOIQVmbXTD5XfxT/wOnYAckyv86lBcFyH1MYDibBrf8ILm2py42NTz9urA=,iv:gztfja90wZEnDax5pR1XuZ0Q6xkjlQVQjQ1YAdU6P8I=,tag:M2rH5+J8umRStheN77SMDg==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.12.1
