---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    app: debug
spec:
  automountServiceAccountToken: true
  serviceAccountName: traefik
  containers:
    - name: debug
      image: nicolaka/netshoot:latest
      command: ["/bin/sh", "-c", "sleep 24h"]
