---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    app: debug
spec:
  # securityContext:
  #   runAsUser: 3000
  #   runAsGroup: 3000
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: kubernetes.io/hostname
  #               operator: In
  #               values:
  #                 - marcus-server
  # imagePullSecrets:
  #   - name: gitea-pull-secrets
  #  serviceAccountName: external-secrets
  containers:
    - name: debug
      image: ubuntu:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      # securityContext:
      #   runAsUser: 250
      #   runAsGroup: 250
      # resources:
      #   requests:
      #     memory: "64Mi"
      #     cpu: "250m"
      #   limits:
      #     memory: "128Mi"
      volumeMounts:
        - name: model-storage
          mountPath: /data
  restartPolicy: Never
  volumes:
    - name: model-storage
      persistentVolumeClaim:
        claimName: vllm-qwen-25-7b-storage-claim
