---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
data:
  block-v6.override: |
    template ANY AAAA { rcode NOERROR }
    template ANY HTTPS { rcode NOERROR }
  private-ptr.server: |-
    168.192.in-addr.arpa:53 {
      template ANY PTR { rcode NXDOMAIN }
    }
