---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argo-workflows
spec:
  endpointSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - argo-workflows-server
          - argo-workflows-workflow-controller
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "2746"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: argo-workflows
  egress:
    - toCIDR:
        - 192.168.10.44/32
        - 192.168.10.55/32
        - 192.168.10.66/32
        - 192.168.10.100/32
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: argo-workflows
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
