---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/sts.yaml
  - manifests/dashboard.yaml
  - manifests/cm.yaml
  # - vmsingle.yaml

generators:
  - ./manifests/secret-generator.yaml
