---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: bentopdf
spec:
  endpointSelector:
    matchLabels:
      app: bentopdf
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egressDeny:
    - toEntities:
        - world
