---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/myanello/homelab.git
        revision: HEAD
        directories:
          - path: argocd/infra/storage/*
          - path: argocd/infra/storage/minio
            exclude: true
          - path: argocd/infra/storage/nfs
            exclude: true
          - path: argocd/infra/storage/garage
            exclude: true
          - path: argocd/infra/storage/local-storage
            exclude: true
  template:
    metadata:
      name: "{{path.basename}}-app"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        name: in-cluster
        namespace: "{{path.basename}}"
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /spec/preserveUnknownFields
      source:
        path: "{{path}}"
        repoURL: https://github.com/myanello/homelab.git
        targetRevision: HEAD
        kustomize:
          patches:
            - target:
                kind: Deployment
              patch: |-
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: ignored
                spec:
                  template:
                    spec:
                      tolerations:
                        - key: node-role.kubernetes.io/control-plane
                          operator: Exists
                          effect: NoSchedule
            - target:
                kind: StatefulSet
              patch: |-
                apiVersion: apps/v1
                kind: StatefulSet
                metadata:
                  name: ignored
                spec:
                  template:
                    spec:
                      tolerations:
                        - key: node-role.kubernetes.io/control-plane
                          operator: Exists
                          effect: NoSchedule
