apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa
  labels:
    app: kometa
spec:
  schedule: "0 */6 * * *" # every 6h
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: kometa
        spec:
          securityContext:
            runAsUser: 3000
            runAsGroup: 3000
          restartPolicy: OnFailure
          initContainers:
            - name: copy-config
              image: harbor.yanello.net/docker/busybox:1.37@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
              command:
                - sh
                - -c
                - |
                  cp -r /tmp/* /config/
                  rm -f /config/logs/*
              volumeMounts:
                - name: config-kometa
                  mountPath: /tmp/config.yml
                  subPath: config.yml
                - name: config-movies
                  mountPath: /tmp/Movies
                - name: config-tv
                  mountPath: /tmp/TV
                - name: config
                  mountPath: /config
          containers:
            - name: kometa
              image: harbor.yanello.net/docker/kometateam/kometa:v2.3.1@sha256:683c04827ef3fecf1cc5cb178f75f91f968aef6c6d89d34bc9c70966fd1d7259
              imagePullPolicy: Always
              command: ["python", "kometa.py", "-r"]
              env:
                - name: TZ
                  value: "UTC"
              envFrom:
                - secretRef:
                    name: kometa-secrets
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: assets
                  mountPath: /assets
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: config
            - name: config-kometa
              configMap:
                name: config-kometa
            - name: config-movies
              configMap:
                name: config-movies
            - name: config-tv
              configMap:
                name: config-tv
            - name: assets
              persistentVolumeClaim:
                claimName: assets
