apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa
  labels:
    app: kometa
spec:
  schedule: "0 */6 * * *" # every 6h
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: kometa
        spec:
          securityContext:
            runAsUser: 3000
            runAsGroup: 3000
          restartPolicy: OnFailure
          initContainers:
            - name: copy-config
              image: harbor.yanello.net/docker/busybox:1.38@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
              command:
                - sh
                - -c
                - |
                  cp -r /tmp/* /config/
                  rm -f /config/logs/*
              volumeMounts:
                - name: config-kometa
                  mountPath: /tmp/config.yml
                  subPath: config.yml
                - name: config-movies
                  mountPath: /tmp/Movies
                - name: config-tv
                  mountPath: /tmp/TV
                - name: config
                  mountPath: /config
          containers:
            - name: kometa
              image: harbor.yanello.net/docker/kometateam/kometa:v2.4.0@sha256:1b2e2d71bc8aaf7830a32219035fd1b92ddb75bbd14575cac649d2f7fbdef951
              imagePullPolicy: Always
              command: ["python", "kometa.py", "-r"]
              env:
                - name: TZ
                  value: "UTC"
              envFrom:
                - secretRef:
                    name: kometa-secrets
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: assets
                  mountPath: /assets
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: config
            - name: config-kometa
              configMap:
                name: config-kometa
            - name: config-movies
              configMap:
                name: config-movies
            - name: config-tv
              configMap:
                name: config-tv
            - name: assets
              persistentVolumeClaim:
                claimName: assets
