---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa
  labels:
    app: kometa
spec:
  schedule: "0 */6 * * *" # every 6h
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: kometa
        spec:
          securityContext:
            runAsUser: 3000
            runAsGroup: 3000
          restartPolicy: OnFailure
          initContainers:
            - name: copy-config
              image: harbor.yanello.net/docker/busybox:1.38@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
              command:
                - sh
                - -c
                - |
                  cp -r /tmp/* /config/
                  rm -f /config/logs/*
              volumeMounts:
                - name: config-kometa
                  mountPath: /tmp/config.yml
                  subPath: config.yml
                - name: config-movies
                  mountPath: /tmp/Movies
                - name: config-tv
                  mountPath: /tmp/TV
                - name: config
                  mountPath: /config
              resources:
                requests:
                  memory: 64Mi
                limits:
                  memory: 128Mi
          containers:
            - name: kometa
              image: harbor.yanello.net/docker/kometateam/kometa:v2.4.8@sha256:c58f6d4af511613f218b6dafbfc84078af4e5a6089790c1fdba58fd7c5dad70a
              imagePullPolicy: Always
              command: ["python", "kometa.py", "-r"]
              env:
                - name: TZ
                  value: "UTC"
              envFrom:
                - secretRef:
                    name: kometa-secrets
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: assets
                  mountPath: /assets
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: config
            - name: config-kometa
              configMap:
                name: config-kometa
            - name: config-movies
              configMap:
                name: config-movies
            - name: config-tv
              configMap:
                name: config-tv
            - name: assets
              persistentVolumeClaim:
                claimName: assets
