---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-vip
    repo: https://kube-vip.github.io/helm-charts
    version: "0.9.9"
    releaseName: kube-vip
    namespace: kube-system
    valuesInline:
      config:
        address: "192.168.10.100"
      env:
        vip_interface: eth0
        vip_arp: true
        vip_leaderelection: true
        cp_enable: true
        svc_enable: false
        vip_subnet: "32"
        lb_enable: false
