---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: democratic-hdd-nfs-controller
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/csi-role: controller
  ingress: []
  egress:
    - toCIDR:
        - 192.168.10.0/24
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
    - toCIDR:
        - 10.10.8.0/22
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
