---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/svc.yaml
  - ./manifests/http-route.yaml
  - ./manifests/cnpg.yaml
  - ./manifests/deploy.yaml

configMapGenerator:
  - name: atuin-config
    files:
      - ./manifests/server.toml
