---
apiVersion: batch/v1
kind: Job
metadata:
  name: vllm-benchmark
  namespace: vllm
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: vllm-bench
          image: harbor.yanello.net/docker/vllm/vllm-openai:v0.28.0
          command:
            - /bin/sh
            - -c
            - |
              vllm bench serve \
                --backend openai \
                --base-url https://vllm.cw623e-myanello.coreweave.app \
                --model deepseek-ai/DeepSeek-V4-Flash-0731 \
                --tokenizer deepseek-ai/DeepSeek-V4-Flash-0731 \
                --num-prompts 200 \
                --input-len 1024 \
                --output-len 512 \
                --request-rate inf \
                --max-concurrency 32 \
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key
                  key: api-key
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
