---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-model-storage
spec:
  storageClassName: truenas-ssd-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
