---
apiVersion: v1
kind: Secret
metadata:
  name: api-key
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:fxPwSZ4ZOsRVxUraEdKU7Py0ToBOFfgUQlfhMJ4GSSwa/Kyd,iv:oOPL0xW0AneyYPWm9pe3Jz/hzzU7Pejr2cE/2izdpaE=,tag:43nrmszyctiEh1rzizohYg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-09-01T23:13:27Z"
  mac: ENC[AES256_GCM,data:lCZmMf2h3MGolQX3WnS/V263UKB4LdcRfI2Snekzhh9GM24dnVSSI1y6trhiKXl28AdNxtd9rkFOeYwA0Xh/PxzbGymFTq2jJHzL6vzVmCnoifCuHLJMspGXhAXbKykVp8ai8ZkBkhBlHDJSRIoiQ2C6Gt5DdkrAHNvHYyswugE=,iv:2o7Ukv8m50gHh4sXDeJYPHOtf9/8o+9wFig72GOGGAg=,tag:npMzI3hoMXVaV2bSyJcD2Q==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
