[all:vars]
k3s_control_plane_vip=192.168.10.100
ansible_user=marcus
ansible_ssh_private_key_file=~/.ssh/id_ed25519
k3s_channel=stable
k3s_version=v1.36.1+k3s1
k3s_install_script_dest=/usr/local/bin/k3s-install.sh
cluster_cidr=10.42.0.0/16
reinstall=false
k3s_oidc_issuer_url=https://authentik.yanello.net/application/o/homecontext/
k3s_oidc_client_id=Akhdo9JGmiOd5ewTIsEqPhcYsHW9v9WmIknoTkWZ
k3s_oidc_username_claim=email
k3s_oidc_groups_claim=groups
k3s_service_account_issuer=https://k8s.yanello.net
k3s_service_account_jwks_uri=https://k8s.yanello.net/openid/v1/jwks

[initial_k3s_pc_control_plane]
pc3 ansible_host=192.168.10.44

[remaining_pc_control_plane]
pc4 ansible_host=192.168.10.55
pc5 ansible_host=192.168.10.66

[k3s_control_plane:children]
initial_k3s_pc_control_plane
remaining_pc_control_plane

[k3s_workers]
marcus-server ansible_host=192.168.10.18
ubuntu-k3s ansible_host=192.168.10.79

[all_k3s_nodes:children]
k3s_workers
k3s_control_plane

[other_ubuntu_hosts]
free_1 ansible_host=150.136.155.17 ansible_user=ubuntu
proxmox ansible_host=192.168.10.77 ansible_user=root
hermes ansible_host=192.168.10.9

[pikvm_hosts]
pikvm ansible_host=192.168.1.9 ansible_user=root

[pikvm_hosts:vars]
ansible_remote_tmp=/tmp

[unused_hosts]
surface ansible_host=192.168.5.5

[ubuntu_hosts:children]
k3s_control_plane
k3s_workers
other_ubuntu_hosts
