---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: excalidraw
  name: excalidraw
spec:
  replicas: 0
  selector:
    matchLabels:
      app: excalidraw
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      containers:
        - image: excalidraw/excalidraw:latest@sha256:f7ee194addd607bf831d2af0f0a34463dd4225e426cf35199ef0b12a803398e9
          imagePullPolicy: IfNotPresent
          name: excalidraw
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "64Mi"
              cpu: "50m"
      restartPolicy: Always
