---
apiVersion: v1
kind: Secret
metadata:
  name: actual-budget-secrets
type: Opaque
stringData:
  ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:3c3vngt54mJxMM7mHdyPUBMC5H4vGVCCOH53zrEpcvhy6AatoRRq8Q==,iv:aaWxCVXOT1jQ4HRYde3s5gmYN5e4N9eUVPNVduk+f9w=,tag:8YnHdHH2+aNSV3aE+0Kb0Q==,type:str]
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:qW//Uu3Z9jHQMZukx+UsLQS8T94pi1uBlaJH9vPVY/fGIxMUwBCwa4ui6q6QHSyA9knxs7ZllOzIJJSfSZVrOv4JXyFu65laYI/4TO74jJwBpHiUl+xwt0ZnSx5KxWByBbT63Aj0VnqyJuhWY/6F9itrrDIhF79NaWABh9zsVGo=,iv:fVTY4Q32fVCcQS1hi0ZkUYuQNLMkAuF+b9NhRPrPVF0=,tag:50e/KEmokjC9F6SlYSW9ug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZU43bmRBSHRMendVdXpB
        ZE5USk9CQ3V0M2NGOFV0OEZPTE1WWjh4a3hjCkVBTXhBR0dWVUhrMzBwTllXYWFj
        Y2dlOGZqTkFLeGcvT1dsbDI0Qm9qc00KLS0tIDUyYjkwYkY5ZGFvQ0loMFBoUGVQ
        UFIyVEUxSi9WakZ0Mi9aME5UQ2RtZzAK9SqkrXBl58wqSM3B0v1UyZRdm4yXtEBx
        Qksoc2zbSpGeVfEi152vhGJqmr8pWa5Fu3sl1XeHGxVpJcONGKHClw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-05-19T22:00:22Z"
  mac: ENC[AES256_GCM,data:ioTUIe9/Z34KPAarJtYK3461G+cpSuuGGd5QOGs0DdNpj/9u4LSwdoUSY2XDj8NZyzgKFGKVme0CvDoQcr1v09M7bpnAsAVCmKSKfZqZffbkbAS9vc6MvmVm7GBfqfrsqTZWth+k8RQ2gLH4aYzixLSXtSNv+81K4aOQXH79i2w=,iv:L1VGVdN5GDxOre9TlkY/YGZ0Gefp3D3uQah5Y+4EHgM=,tag:EP2tARTfr0/kffKYQbVuIQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.0
