---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: actual-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-budget
  serviceName: actual-budget
  template:
    metadata:
      labels:
        app: actual-budget
    spec:
      containers:
        - name: actual-budget
          image: harbor.yanello.net/ghcr/actualbudget/actual-server:26.5.2@sha256:1aeeb3985db55556e716dec25e08f6ce09308c2571b65cddbc6746ee6d5e0d45
          ports:
            - containerPort: 5006
              protocol: TCP
          env:
            - name: ACTUAL_OPENID_DISCOVERY_URL
              value: "https://authentik.yanello.net/application/o/actual-budget/"
            - name: ACTUAL_OPENID_SERVER_HOSTNAME
              value: "https://actual.yanello.net"
            - name: ACTUAL_OPENID_ENFORCE
              value: "true"
            - name: ACTUAL_OPENID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: actual-budget-secrets
                  key: ACTUAL_OPENID_CLIENT_ID
            - name: ACTUAL_OPENID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: actual-budget-secrets
                  key: ACTUAL_OPENID_CLIENT_SECRET
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: truenas-ssd
        resources:
          requests:
            storage: 2Gi
