---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: actual-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-budget
  serviceName: actual-budget
  template:
    metadata:
      labels:
        app: actual-budget
    spec:
      containers:
        - name: actual-budget
          image: harbor.yanello.net/ghcr/actualbudget/actual-server:26.5.2
          ports:
            - containerPort: 5006
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: truenas-ssd
        resources:
          requests:
            storage: 2Gi
