---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: forgejo
data:
  config.yaml: |
    log:
      level: info
    runner:
      capacity: 2
      timeout: 3h
      fetch_timeout: 5s
      fetch_interval: 2s
      labels:
        - forgejo-runner:host
    cache:
      enabled: false
    host:
      workdir_parent: /workspace
    server:
      connections:
        forgejo:
          url: https://forgejo.yanello.net/
          uuid: ea1ce480-004b-4769-b7cb-cf071541f397
          token_url: file:///etc/runner/token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-runner
  namespace: forgejo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: forgejo-runner
  template:
    metadata:
      labels:
        app: forgejo-runner
    spec:
      automountServiceAccountToken: false
      containers:
        - name: runner
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 2Gi
          workingDir: /data
          image: harbor.yanello.net/library/forgejo-runner:v13.2.0
          command: ["forgejo-runner", "daemon", "--config", "/config/config.yaml"]
          env:
            - name: BUILDAH_ISOLATION
              value: chroot
          volumeMounts:
            - name: config
              mountPath: /config
            - name: token
              mountPath: /etc/runner
            - name: workspace
              mountPath: /workspace
            - name: containers-storage
              mountPath: /var/lib/containers
      volumes:
        - name: config
          configMap:
            name: forgejo-runner-config
        - name: token
          secret:
            secretName: forgejo-secrets
            items:
              - key: runner-token
                path: token
        - name: workspace
          emptyDir: {}
        - name: containers-storage
          emptyDir: {}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: forgejo-runner
spec:
  endpointSelector:
    matchLabels:
      app: forgejo-runner
  egress:
    - toEntities:
        - cluster
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
