---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secrets
type: Opaque
stringData:
  key: ENC[AES256_GCM,data:hmZt5yfsY/jXwaZIwfo8KfOU3dQxZ2XMSjwA9xy3sCw7Oyj2QerJyw==,iv:qrfZ6ey6K/sWDs8GnbWQj0kuBwONUwb0jOhQQfK71Ys=,tag:3mWsJB8JubWl3A9+5m8kuQ==,type:str]
  secret: ENC[AES256_GCM,data:K3VOwGhCZtLjOjKykonX7DGJEyC+rMjD+zQmzpcLJdS6NJ9pQoshZRdzGEgr3i+FyFlIVX4+mNKKEms6wyqNQHlSYnQl69KTDgZA4iRZvO52WKApcuo/YBpZfXQQrv8yZHQkrsKYPmvIULWz8ZadbMdfN7cE3c5k1fIlTDubJWY=,iv:Z1Ln5JiL+YgOVvlvZHoTQlI32Fy3WLyvTN+0N6zq9G0=,tag:L5iDi2Tj6QSeFzvhi+nM9A==,type:str]
  username: ENC[AES256_GCM,data:BAmQYYExAMF7aV2mBw==,iv:C61ms2H8kRRswCj1Led01wxq22vr3vVF53mS0lnXTik=,tag:amnPvg0yBJYfCdhc2YYTiQ==,type:str]
  password: ENC[AES256_GCM,data:ziulzFW1F6uXpl3orTOi,iv:RlUlP/x4cK+kQe2enV2I4QxAV6DD+M1luWJoYcHJ1ig=,tag:MTecTmnmtWguTE9TBecsAQ==,type:str]
  runner-token: ENC[AES256_GCM,data:qbsmZs2iVZ59EGz0WOG+apLCNfTNLnZaCxmQvOOujb7Q99HPOBOik+soxw==,iv:iWtlPQse9faStDNNn0S+qhD7vnYG7V0QLYjvHYvAvdE=,tag:yaAZnKqn2x+k1T7/Zdp2jg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-06-09T00:12:26Z"
  mac: ENC[AES256_GCM,data:IIeOCxZwDUO29mXw4qb1ph9jYdlqJedU2vtIB6v3bFBIcVTk1sGXSvJYcBvT+UyyM+B8MOzsG3EAzO9C/tm8s6sGVXwagH/hVDD2v2d1yLY9FI3xx5rb+4mbQAzEfLXeEV/jGOXvAF1EpVle9Nz42xMon8E2Fnyznn+uUmva8UM=,iv:FS0pgivjlabjhACOVALpXh5F3ob3xevGcNku2LaKwDI=,tag:TbHQ8jFjTZek7b6a6QmakQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
