---
# yaml-language-server: $schema=none
- Infrastructure:
    - OPNSense:
        href: https://opn.yanello.net
        icon: opnsense
        widget:
          type: opnsense
          url: https://opn.yanello.net
          username: "{{HOMEPAGE_VAR_OPN_USER}}"
          password: "{{HOMEPAGE_VAR_OPN_PASS}}"
    - MySpeed:
        href: https://myspeed.yanello.net
        icon: myspeed
        widget:
          type: myspeed
          url: http://myspeed.myspeed:5216
- Media:
    - Tautulli:
        href: https://tautulli.tautulli:5216
        icon: tautulli
        widget:
          type: tautulli
          url: https://tautulli.yanello.net
          key: "{{HOMEPAGE_VAR_TAUTULLI_KEY}}"
          enableUser: "true"
          showEpisodeNumber: "true"
    - qBittorrent:
        href: https://qbit.yanello.net
        icon: qbittorrent
        widget:
          type: qbittorrent
          url: http://qbittorrent.qbittorrent:8080
          fields:
            - download
            - seed
            - upload
