{
 "title": "Iocaine (Generic)",
 "description": "The deadliest poison known to AI",
 "tags": [
  "iocaine",
  "self-hosted"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(iocaine_version,job)"
    }
   },
   {
    "name": "hosts",
    "label": "hosts",
    "query": {
     "query": "label_values(iocaine_requests_total,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top trapped agents ($hosts)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(iocaine_requests_total{job=\"$instance\", verdict=~\"accept.*\", host=~\"$hosts\"}) by (user_agent_group))",
     "legendFormat": "{{user_agent_group}}"
    }
   ]
  },
  {
   "title": "Top sites ($hosts)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(iocaine_requests_total{job=\"$instance\", verdict=~\"accept.*\", host=~\"$hosts\"}) by (host))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Outcome distribution",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    {
     "expr": "sum(iocaine_requests_total{job=\"$instance\", verdict=\"accept::garbage\", host=~\"$hosts\"}) / sum(iocaine_requests_total{job=\"$instance\", host=~\"$hosts\"})",
     "legendFormat": "Garbage"
    },
    {
     "expr": "sum(iocaine_requests_total{job=\"$instance\", verdict=\"accept::challenge\", host=~\"$hosts\"}) / sum(iocaine_requests_total{job=\"$instance\", host=~\"$hosts\"})",
     "legendFormat": "Challenge"
    },
    {
     "expr": "sum(iocaine_requests_total{job=\"$instance\", verdict=~\"reject.*\", host=~\"$hosts\"})/sum(iocaine_requests_total{job=\"$instance\", host=~\"$hosts\"})",
     "legendFormat": "Reject"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$instance\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 4 },
   "targets": [
    {
     "expr": "iocaine_version{job=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Depth",
   "type": "stat",
   "description": "Maximum depth of the explored maze",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(iocaine_maze_depth{job=\"$instance\", host=~\"$hosts\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "description": "Total number of requests served",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iocaine_requests_total{job=\"$instance\", host=~\"$hosts\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "stat",
   "description": "Total amount of garbage served.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iocaine_garbage_served{job=\"$instance\", host=~\"$hosts\"})",
     "legendFormat": "Traffic"
    }
   ]
  },
  { "title": "Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU time spent generating garbage",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Resident memory size",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(iocaine_requests_total{job=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}