---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: adguard-exporter
spec:
  selector:
    matchLabels:
      app: adguard-exporter
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      scrapeTimeout: 10s
      interval: 15s
