---
apiVersion: v1
kind: Secret
metadata:
  name: adguard-exporter-secrets
type: Opaque
stringData:
  ADGUARD_HOST: ENC[AES256_GCM,data:r+QY9zsV0PfGGC8Mq2FqHhs+T57Nk4A=,iv:H8li1IpldI+9DKCrY45dTAaZcHzRSjnEhunDeaA/o9I=,tag:y9rtxTh+hzrV7bEYqcsczw==,type:str]
  ADGUARD_USER: ENC[AES256_GCM,data:UlSuy6nt,iv:0u2UmWvbnRt5peBtHtZvvITK44uPwvZbiLQ2Hg6n/UY=,tag:rGhCHJNBhBVpa+uTYzlrPw==,type:str]
  ADGUARD_PASS: ENC[AES256_GCM,data:PDLd98fKD9NNpfXLlBM=,iv:Tq1fR0JRBLaWYphoWwJiBpTPRk9334yROqNdkyWxzGQ=,tag:SkSJfQBakViKODwdzqmt+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMFFvcHNYV2ZIOVJEWkJO
        c0RneXhxcU85YzdqbXJKck4zQ1VlM0lxWUdVCnpQaXl1N2REQjFXL1Z0NDVicGNM
        VllYYUVUNUVWcWxBSFZ4WXVRQ2RINGsKLS0tIGtCRStJT0l3L0ZJc002V0VqNWlF
        RGp1a1VldFQxNDd5ZzNZVi9JenVka0UKZIUczSZ99bQYUQhZGm6SmrY4fJyBP21Z
        VRC/VfwK92j3IhX8MzfytWmL5fdV6Vxdfljl4AIBGyNgrRGsT05b/w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-08-31T18:10:40Z"
  mac: ENC[AES256_GCM,data:V3+QTZaMENXl6aKu46v1BUM5WGfH7Lh9xfG+4a8XA9j9nOYO64o1yjdFdnMBrv9U7X/6xp+5wL1baDbNa3+22jL/5y4HkYYDO9DKJpveuohEOvuk5hOirM0M7LSgKgIPygZhmm90Jjdi7KnINxUyWGWqvBupD+9jti9/nt+8J7E=,iv:V0w+wQVPmohAvJr+j01UFLTxZTdQVavUleb7pOk+wnU=,tag:1lIC1bkd0zEK+EfOsm6MMA==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
