---
apiVersion: v1
kind: Secret
metadata:
  name: unifi-secrets
type: Opaque
stringData:
  root-password: ENC[AES256_GCM,data:JuCDfScexR3AEa8FeW9FDJNf7jusL9q0JSPEvC/D8tD0KL6UVqEyHq/ruLdrMUX3,iv:PDFds66B9ZPSPS+ZF2VXS37gksZel70LADPSL5jxDnU=,tag:4zC+KcTdrNSdGG03N9l+Bw==,type:str]
  unifi-password: ENC[AES256_GCM,data:mxz0x7g4zNwZpIz5H2pOMyjgn+T4505u0SvLb1wY7+0hLHN+Cq8Caa7hx3FKPDs1,iv:QcW+GIX5DpSZKvAhElxilIMVOWjvDIppgMUZhzl92cY=,tag:yGUX9eAcWv+yUwoR8ujfFg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZFdPcHJVV285T0JmZFIy
        SXJZSEMyYVoveDRvOU9uMTJDTzd5ekhaTmdVCnc3NklPa2tnWWNVSmRQZHpUOWJt
        Z0RpUlMvRjFKVndIa3p1ek95WTN1b0UKLS0tIFA2RkRZTEVMQjVlWjE2TCs1S1hF
        TS9VckFMSjNGaDVEUnkwbzB6d29GWFkKjfTNt5mbqttfjs3a/UlVNwD/tEMF4ZOZ
        5PzNZvubQ+P+wmdlykbhApAfbsGlg1npGCGxIs7NL1pdgVw2tCluYQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-07-24T13:29:18Z"
  mac: ENC[AES256_GCM,data:nPzRxaR0el3UqcqOChoMQDoXuO73/9LaIP7XTtGdaDajskPDG/EUt3l8RE1e7J4+jv/rBIgiwL47IMnKNxAtBjcntjZHumQ2w3G/ruP2gbVAMcHSF4tR2u7BbuQAZETGYI58ITzz5yGRq6DLT6fy1XALBYbvoFHzStAgreWUJ6A=,iv:6c4TB8wXd0ySGpizVlrh73A1edwOEy+2F+NMdIDe+DU=,tag:nW3x6VXbecv4SZNwuNRlBA==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.2
