---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: unifi-mongodb-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./manifests/secrets.enc.yaml
