---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: unifi
  name: unifi
spec:
  ports:
    - name: webui
      port: 443
      targetPort: 443
    - name: device
      port: 8080
      targetPort: 8080
    - name: hotspot-secured
      port: 8444
      targetPort: 8444
    - name: stun
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: discovery
      port: 10003
      targetPort: 10003
      protocol: UDP
    - name: syslog
      port: 5514
      targetPort: 5514
      protocol: UDP
    - name: speedtest
      port: 6789
      targetPort: 6789
    - name: rtp
      port: 5005
      targetPort: 5005
    - name: id-hub
      port: 9543
      targetPort: 9543
    - name: support-files
      port: 28082
      targetPort: 28082
    - name: aqmps
      port: 5671
      targetPort: 5671
    - name: hotspot-redirect-0
      port: 8880
      targetPort: 8880
    - name: hotspot-redirect-1
      port: 8881
      targetPort: 8881
    - name: hotspot-redirect-2
      port: 8882
      targetPort: 8882
  selector:
    app: unifi
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  labels:
    app.kubernetes.io/instance: unifi-app
  name: unifi-tlsroute
spec:
  hostnames:
    - unifi.yanello.net
  parentRefs:
    - name: cilium-private-gateway
      group: gateway.networking.k8s.io
      kind: Gateway
      namespace: cilium
      sectionName: unifi-tls-passthrough
  rules:
    - backendRefs:
        - name: unifi
          group: ""
          kind: Service
          port: 443
          weight: 1
