---
apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
stringData:
  RADARR__API__KEY: ENC[AES256_GCM,data:ljmGS/tPqdav88CbEiskkGkKUWnvwLZIQ/iIvziA7Z8=,iv:pi+L9EIsfzU2J+G9TNvqAxyfpiCtsQQ1h7ebnHBr+Ig=,tag:8C16Ysb86192ETgWaW+a8g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMGh2dFZJZzQ3aU1DbE04
        b2tUQVFJQWpIZUkxZENlVmxlbm1IRWJjaHlRClNPSXNRTXpVZmpBWkVpeGN1VDRa
        NTFiNVdNTE4vVXRVaTdKNzBZZy9sN3cKLS0tIDNJQUVKc25pc29Qd1hOTmExQTJz
        SDVFc09LVnRhb1UwSmlOL2F4dnVCVlEKDirZCZQhMt6KPkywh9Vw+juHAFeZmcJ/
        oYgpJqXZmFAheqDEJO2OJDBugzS5+mZ9B1WVs2qy69PMKL/yQsKvaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-06-24T17:02:21Z"
  mac: ENC[AES256_GCM,data:QsQnYjQYIUkV4mXzuAbLvktYuzWLOCsHO+1ECG3aRr4RJG2LBY63c/P03QZX0G0/uWP7m8rtD5mzzXjXnPGozA1Ske2Ei+gFIBNU+cO9G4y90qH8k+mB7GrvBbStHmvX5Rii61ce6g0/1ICeLwQ31OD6zXOn2QvJ7xTKvln0b5g=,iv:saAxxv1zVdDVVCmAuMNvTseiplMXUAfZzhqkn2UOeBw=,tag:TgqFN0VZqkBl0ssReudbHw==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
