---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: profilarr
resources:
  - manifests/deploy.yaml
  - manifests/parser-deploy.yaml
  - manifests/parser-svc.yaml
  - manifests/svc.yaml
  - manifests/pvc.yaml
  - manifests/http-route.yaml
