---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/deploy.yaml
  - manifests/service.yaml
  - manifests/pvc.yaml
  - manifests/cross-seed.yaml
  - manifests/http-route.yaml

generators:
  - manifests/secret-generator.yaml

configMapGenerator:
  - name: cross-seed-config-file
    files:
      - manifests/cross-seed-config.js
