---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rclone
  labels:
    app: rclone
spec:
  replicas: 1
  serviceName: rclone
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rclone
  template:
    metadata:
      labels:
        app: rclone
    spec:
      initContainers:
        - name: generate-htpasswd
          image: docker.io/httpd:alpine@sha256:1b766f17b84026429b7cb243317b142921b24432336e798bc881c43f45ed9567
          command: ["sh", "-c"]
          args:
            - |
              htpasswd -cbB /config/rclone/htpasswd "$USER" "$PASS"
          envFrom:
            - secretRef:
                name: htpasswd
          volumeMounts:
            - name: config
              mountPath: /config/rclone
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 250Mi
      containers:
        - name: rclone
          imagePullPolicy: IfNotPresent
          image: docker.io/rclone/rclone:1.75.1@sha256:45401ad7410db1d67ffdb58e19059ad20b0d8e0285a60e38bbec55cc1019c7a5
          args:
            - rcd
            - --rc-web-gui
            - --rc-web-gui-no-open-browser
            - --rc-addr=:5572
            - --rc-htpasswd=/config/rclone/htpasswd
          ports:
            - containerPort: 5572
              protocol: TCP
          volumeMounts:
            - mountPath: /config/rclone
              name: config
          resources:
            requests:
              cpu: 150m
              memory: 1Gi
            limits:
              memory: 1280Mi
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: truenas-ssd-nfs
        resources:
          requests:
            storage: 1Gi
