---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/http-route.yaml
  - ./manifests/reference-grants.yaml
  - ./manifests/cnpg.yaml

generators:
  - ./manifests/secret-generator.yaml

helmCharts:
  - name: authentik
    namespace: authentik
    releaseName: authentik
    repo: https://charts.goauthentik.io/
    version: "2026.5.5"
    valuesFile: ./manifests/values.yaml
