---
apiVersion: v1
kind: Secret
metadata:
  name: lumo-tamer-secrets
type: Opaque
stringData:
  LUMO_VAULT_KEY: ENC[AES256_GCM,data:GnEn3rRbyghse74XZanhCh0/6QwNewTWKFyVb4rqZbEbO8Mn374pQUX+Uk8=,iv:58eWxwzsQ9SLVxPFcBeDwW0FSP3tBeXpKsNZJKUYjik=,tag:MIkdtFTU+JzQqJOKkPRsJQ==,type:str]
  API_KEY: ENC[AES256_GCM,data:qs0Hu85QMx0RWoQFTdfjOthJgjNKwEt2xaEhO1gN6fvF7V0L1NawK4D3mv6/9lKQ,iv:BNBxSQIb/z1ojxZfR/43H7iNuxLjdRrByuXn634PltQ=,tag:IYhbFdY9N589aLLdt1So0A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N25KRFBlSktiN0tsajBx
        b1lOYlZlLzZ2L0p4WVBXbEpJT1pNcCtsSkNnCk8xVTN5K0JjSzVWc0R2cnFndUMz
        QjNPUTJmNFQwUnE0c212czRyVGxvbzgKLS0tIFVUK2FuTlNtbUszYk4yQndhWVY1
        L0JMakhOb1FEVWlGMVJtT0JPc1ZSVVkKTyy+rs865doR1jETuUiIIrVQxDUendFj
        TMQZbmO5gp/FXRG/Mvojp1IWsquB7vr9BQSRJ6w3sYidHoDbG53h0A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-06-06T16:37:47Z"
  mac: ENC[AES256_GCM,data:bCO1+oSKDnh3+N8f7skEwR45+bq38o6fEesrHp7bcoRdhvuTI8oVYYBAiPEokk/Fu5b2RhyVhw2gu89o8ylTij9pCfxbS/0Knc2F9a2pl0P1ZVBFy0Y8p/Z3aZ8PSpSt7xoNFqpUgPh6cgUywFASe9GUwdXS6JUI218xb77dIDo=,iv:gkK/SFeUxyL8WYnyyghae+vK8d79pAjKtTgKn5G8XYc=,tag:V+1kmAWvPqzVsa+s3oXy7w==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
