---
apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
stringData: ENC[AES256_GCM,data:yF65pF49WbiGvpaF9lis0Y7m595scZ6vUqoXy7p+60v2HE5o0QMamDJSwo0X/awWHBgbQrNmJ448LchkC8e9x2tnLHCR/BOY1kOfhy7mtnHdWtVcQRilYC3SkSRhDBsneaSock7c17HdfTRBJpE//8PN+XNulae5nXFCIQByaa/T7MaU9AQBQexEtANvLWwUO7iKZRsCErLpgUbPa6AsEsQQ3CMameGlK27l1txndQch20oFYYA+JtQyVSQ/C0Tzj2lI5bQZOGIw02Fej8cYrvScmbNH3SRo1N7g3M5jzRnhlHi/hSpRVgdP/hQ5FrwcH4JRSVGAlkvBGcu5C1epNaqeQVCITAYOGtsf12YQ6jzecm/OKGGbvQDNXAGTq8kFYR//C5kCgah6nraeo4P3Wn77CVbKq0RXaGiqs34QPTIg9sRzzGfmuabPnQtw/EyvXHv2Wkm0UrNMTJZk0OWoJpM0/N6F5ND2x1XHMm9SGksVhUMLkc5HGNqOIOx6prGKKKvhbHmCZMOp/5qkl+Xh4JYEvW/PQsN6a5toyFspDaJjE/HcprqW9EZn8Vtsis+wHCToDMaQHqJASBn/NDPcXspPrTH6itqB7ALSY4sUkzeniy0PcaEXZJDOWJBgac1BKaxO01Nh7HX9Nik87PSBeoAaFPx+ZHqxqDDHJx1ssW45Ahl1Y+lLnyA8/qByPy/jX2g3YTlWqS8QOgOWIHpKSzOZXVp026ASFj6BsPsGXZ+FMX9nm1nQ8wjw8ynvQSQsmpxKsiEPnvQXqCFW6NpEwtXWMrQubMo0vdUbQDgJ1PEMDd2YV5J3Ko8d0nY53z6TCDh8hZTTvGkKdUthrPC47SayIpF7hmI+ZOpvwQbJIYaUFkyRWsmCsS3HVe5t/RvUSDsd+lzCw75bdTF7QlgSn+lCu/Kryjnqk5ZZCTK5vi1N4DlIQSkYuOw5TyJCkQVSBSMYMP0433Sm0bGXTRdbx8svGjPPqh1ePBNahhj1UHhoEr/BlaS/iG64+J1f1hv+rChKZFwlUDIwyZKFf2PvWPddx6fxrU+BAhARCOUnzG4wt7zCxEaGp6o=,iv:iRukO6v8OIHNqGf6SH5Vk6y/dOutInxp/EZxwuDdA9o=,tag:1cOrHepDvIBWNR0kAz9enQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-06-24T13:06:50Z"
  mac: ENC[AES256_GCM,data:tkdovXMoI+mrbCGQTtZBfFEBfLInVL9QiZ/51eNi3L/Y42gx05/xilHvgfB5OU7fKy0CXA9f0zKv+St0IrDzj4sH/n0qGci9DcqSXa4mxTQP4GBZQujBnlWBFomvdYH1BYdZSl7P/OmrU1Z9b4QIqnbnVvGVNRlgd3ZffqWB1NY=,iv:UBfwKGvx7Y5bt4cE/QtcK5fGLLlMw+UzWjwQAh9HWak=,tag:0PMEY7P48RqmUW+2nvVtRg==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
