apiVersion: v1
kind: Secret
metadata:
    name: config
type: Opaque
stringData:
    SONARR__API__KEY: ENC[AES256_GCM,data:xMEp211bytpGGEf8vgb5+Sar1JvSYIJMiBx/ukMFi6A=,iv:g33p6ZaDbpufhLb0wjmGMTntYRSwSaTQs5h1mphHE1c=,tag:54rimGAmBKO1w7AKf40jbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvanhmZDJuT2Z4K3ZPWEUy
            OTJwR2VmUTNyZkhaNkx4WGVkcVVXU0Rzd3lrCjdLdlhNdU13c2lTOThreVZkYUxx
            MkV2U3FTUGJEUktjclYxWEFVR2RmUzQKLS0tIGcvQWd6WG84Z1RYMHZ2NE9WdUEw
            b0w1QzBaSExCaWh6dGR3TVM2VlJYMncKWHv/Y480UZpaHKI3lqJcJi/pLwAbkAx1
            5OitCdpHOZjZJDJQqmJ5ThmY4ZHoCTk9gA7PiuBSoFsigNCWZZIY6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
    lastmodified: "2026-06-24T16:35:21Z"
    mac: ENC[AES256_GCM,data:DQeQ39u5/2MJt8RCBEneMRulAA67g86DVDJuvABKppc8mwb6BNt7v56Y8zm+dl0GgcL5p7XPTO1Zb/5yxX1kEaDw9tgzC87MN4poItbvUQJ7onYl/VLJjnDB1sGoUxlvSpnOk2UQGHMaj6A3GcQSQZHOpc4E+7t/d3L8o6R128E=,iv:7F2zVo1uYe2WfJMy3YD6ckoGUNsGivZXA4G9NdR9ukY=,tag:OQR6v3XuDqI6SjmT1Pl7tg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
