---
apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
stringData: ENC[AES256_GCM,data:ttBkRaqiQ5En9BlRf/kl79ZPI9yJ+UCJQLDA63KS/jJfDuczPrsRzluc5jdHQt+x+Wehd/4TL4yW0cyiSToOYUV1iQoV+iq1qdchrfrrcKox7VZl/ZlNLBmdxk4QBZ12mHdBKO5A8CmKW0/FcjGiJM0EbNtJ2yZqZnWl2XkILtvcPlgDKinRBpK2X4zSXEJ4Id56G48/bwn67ybvm2+Zz89qeGaVoqasAWkYDloiXK+eZyLFAYCCq0gCTRMKalwyUoiP+c5BRNsE+uVLV37YaV1E4L9zilaDbgmRAwP2fF2KEGBH/atO6AzffX3KhUJ6Sxe+fx5sPcsMTo0OxO5HXqlAM/d28qZKA2nQzpmKGlxn+Zz76m8mCeqe8dnCeFybKnvA2ilU/G4RQi0aLy5ccjnr08LlEkkb+c/9ZjWJ5jtJ1gZWYRt+KVjlvPGYUh1RR1wiPf6nXXnHkAUBXbIYbY2pxPva2XLtN5CvM47fgVpW1nT7iPqwFiCn6YjukSTFoKgXwAduZf4PMmBxhAF86R25HvABFt9dWYbIWsYMls/eWlRowvmKxlOGbkent4RY/o6TpSH5EpoyWIAeFpl6COCASaKawrX8naeQnejUlPX//9XBI8ZfKY4EfTCUocFDLOS1L1XHJ9YZ+DzNypX6aLJfPhiAG4QoRYNIf+c7Q3d4zgvR7uBYGGLkviKNnbZQOenmFPH60P4VZHV2kV+heMnTsARcWfqIIm+72Y4Yu6WUbVw9BHJL3LCvM1i4wp6rj7lEqYvpJj7P2ko2HVHbGw5wUGFSZohT35w4gZSUAmBwqdvtvzcaphKZb9VuCWpw5RmKRa8lsFzlLjWxzlb9Xjgahck5rHDR5uvQOtHU2CSXE+nFjdLy3VTat7sjPzLAWLj6nM3Lget3op7DGnq8G6wV1sKJWtWrpJvXjow2Zl/LBIrm7KhIpYAQh1kf56D6hXpw/pUHpByHlPgf+9SpxJU6Ha7Mh4s/jgL0Zl5ATuE5nRtyqoqt33jyMnVG+fkMt/pYAjjMYcUvXP8fXjVpvwT6tw==,iv:8HzbHEh05MKk8IcpFyBlGiAZKrbpz2GBCR1Yn9Ey4cg=,tag:x5abNJsFcBAhaKlOeac8ew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
  lastmodified: "2026-06-23T18:31:43Z"
  mac: ENC[AES256_GCM,data:iXXIkomCy8/q7tIs8hClrTwXqctrNnajTFd34+/HT4cm3pxT9ocg5KfVMjPocMkuTbtlZEUFCj7pYA1CKHb6IwQgnPM2YeZmYVInJby9zRiIAKbAQ6qVpHaO52Lz3K6dBMocr4dJEqXXrVaHgaGo//1wOfBBSQqbm1OPuSNhrhw=,iv:Q6aAJpc6R0CIR56LnouTnXvrTM/OfxIyKUH+tRuiIR4=,tag:WsZWmV4JA8hGKIlbzz3cjQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.1
